* DONE Jyrki Kivimäki ja Dzoukki-kirjat                      :kirjat:huumori:
CLOSED: [2013-04-16 Tue 14:51]
:LOGBOOK:
- State "DONE"       from ""           [2013-04-16 Tue 14:51]
:END:

Järin omituista on, etteivät nämä kirjat koskaan levinneet
pitkälle. (PC) Dzoukki -kirjasarja on nimittäin viihdyttänyt monin
painoksin vuosilla 1995-2006 ja ne ovat monia kultaisia juttuja ja
nostalgiaa 90-luvulta täynnä.

Kirjathan ovat seuraavat:

- Dzoukki '95
- Dzoukki Y2K (1998)
- Dzoukki Y3K
- Dzoukki XP (2004)
- Dzoukki 2006

Näistä kirjoista oleellisin on Dzoukki Y3K, jota onneksi useimmissa
kirjastoissa löytää. Niitä kai hankittiin Kivimäen nimen
perusteella hyllyyn sen kummemmin sisältöä tutkimatta. Suosittelen
kaivelemaan tavallisen kirjastonne hyllyjä, sillä nämä kirjat ovat
kultaa. Olen aikani metsästellyt opuksia omakseni ja vain Y2K
puuttuu hyllystä. Hieman tarpeetontahan sen hankkiminen on, sillä
Y3K on pitkälti uusintapainos Y2K:sta useilla lisäyksillä, mutta
myös muutamalla poistolla.

Tämän sarjan kanssa oppii niskoittelevista käyttäjistä,
koodaajista, mikrotuesta, johdosta. On johtajia, taloushenkilöstöä
ja koulutusviikonloppuja. Kaikki erinomaisen hienosti rakenneltuna
kieli poskella ja erinomaisen kuivakalla kerronnalla. Kirjat ovat
hyvin mielikuvituksekkaasti ideoituja tosiaan. Ja työt ovat
pitkälti kaikki 1990-luvun fiilistelyä aikakaudelle ominaisten
juttujen kanssa. "Kuka haluaa alustaa levykkeet tälle kurssille?!"

Minuun nämä jutut upposivat jo pojankloppina, vaikka kaikki
bisneselämään liittyvä ei aivan selvinnytkään. Sitä sitten vähän
kerrassaan oppi enemmän ja enemmän. Sääli on se, miten vähän
internetistä löytyy näitä juttuja. Paolo Rytkösen raideria koitin
googlailla, mutta mitään fiksuja tuloksia en löytänyt. Ehkä
lähitulevaisuudessa tämä postaus oleilee listan kärjessä.

Ernst W. Hakkarainen on toinen kova, mieleenpolttunut hahmo.
Uusmediakoodarit Marco ja Hemmo-Joachim samoiten. Sepposen ja
Tepposen Formula Notes -tappelut nekin. Puhumattakaan huvittavista
case-tapauksista, joita voi todellakin kehitellä loputtomiin.

Vaan taitaa Jürgen von Steinhugel nyt olla luovuttanut pelin.
Viimeisin kirja jo liikkui uusille urille, eikä ollut aivan Y3K:n
veroinen. Paluu 90-luvulle olisi liian kornia, ja hankala olisikin
panna paremmaksi sillä saralla. Mutta olemmehan me kehitelleet
2000-luvullakin paljon hulluja juttuja ja erityisesti kun
kokonaiskuva on kehittynyt...
