* DONE House MD                                                      :sarjat:
CLOSED: [2013-02-04 Wed 18:20]
:LOGBOOK:
- State "DONE"       from ""           [2013-02-06 Wed 18:20]
:END:

Tämä sarja alkaa olla kohta katsottu. Kahdeksatta ja viimeistä
kautta on jäljellä muutama jakso, jotka katson seuraavan viikon
aikana. Nyt onpi aika kirjoitella mietteitä tästä.

Sarjallahan on mitä kutkuttavimmat lähtökohdat. Mestarilääkäri,
joka tekee asiat omalla tavallaan ja mausteitahan riittää. Uniikit
ihmissuhdetaidot ja olemalla alansa paras tekee hyvän ja
realistisen kombinaation. Tässä asiassa tietysti ollaan ajan myötä
hieman hypelty, mutta sarjahan on ollut parhaimmillaan pelkkien
hahmojen varassa ollessaan.

Tarkoitan sitä, kun sarjan draama on kehittynyt pois
lääketieteellisistä ongelmista (ehkä draama ei koskaan ollutkaan
siellä -- alkupään kausia en muista juurikaan) ja erikoisjaksot,
joissa lääketieteellisellä potilaalla on huomattavan pieni rooli,
ovat niitä hienoimpia.

Kullakin kaudella on taipumusta alkaa hyvin, mutta heti sitten
vaivutaan pieneen ahdinkoon tai tylsään, harmaaseen massaan.
Massasta noustaan kehittelemään kauden kliimaksi vasta puolivälin
jälkeen, jolloin taso onkin sitten erinomaista. Näin tehtiin
ainakin vitosella, kutosella ja seiskalla. Nyt katsonnassa oleva
kahdeksas on ollut aika heikko tässä suhteessa.

Housen kanssa on niin helppo samaistua, minun ainakin. Välillä
naurettavan yksityiskohtaiset analyysit toisten elkeistä ovat
toisaalta muodostuneet klassiseksi kliseeksi, mutta pysyvät
kutkuttavina. Ja Housen ongelmanratkaisumetodi varsinaisen työnsä
ulkopuolella on sekin viihdyttävää katsottavaa.

Ensimmäinen iso merkki sarjan erinomaisuudesta tuli jossakin
kolmoskauden jaksossa, jossa unimaailma dominoi monessa pisteessä
ja taiteellinen näkemys oli erinomainen, suorastaan lynchinen.
Paras kausi mielestäni on ollut viides. Vanhat naamat lähtivät pois
kolmannella ja sitten neljännellä mukaantulleet alkoivat
viimeistään upota viidennellä sisään. Ja jaksot olivat mitä
nokkelimpia silloin. Dialogi ja kaikki. Ja viidennen kauden lopetus
sitten viimein ikuisti koko sarjan.

Vitoskausi asetti sarjalle uuden riman. Valitettavasti myöhemmät
kaudet eivät yllä mitenkään yhtä pitkälle, vaikka sitten
kutoskauden päätöksessä kutitellaan hienosti siihen suuntaan ja
seiskakaudella on omia, erinomaisia häkkyröitä.

** ...where we came in?

(Päivitystä 29.3.2013.)

Kahdeksas kausi päättyi odotusten mukaisesti ja en sitten
malttanut olla ilmankaan: aloitin ensimmäisestä kaudesta
seuraavalla viikolla.

Alkujärkytys syntyi kahdesta asiasta: ensinnäkin kaikki ihmiset
ovat nuorempia. Noin 8 vuotta nuorempia. Hyvin nuoria! Mutta
isompi mielenkiintoisuus on sarjan alkuvaiheessa seurannut tyyli.
Hyvin taiteellinen ele on ollut alusta alkaen ja kaikenlaista
fotograafista kikkailua on ilmassa. Ja minä kun muistelin, että
sellaista otettiin vain hiljattain käyttöön kolmannella kaudella
sopiviin paikkoihin. Pehmeätä valoa, lievää bluria. 

CGI on mukana alusta alkaen, sen kyllä muistin. Alussa on
tavallaan mukava, kun otetaan sellaista realistista
lähestymistapaa lääkäreiden tekemiin löytöihin. Myöhemmillä
kausilla ne -- kuten on kannattavaa -- ohitetaan turhana toistona.
Wilson on yllättäen isona mukana pilotista lähtien. Tätä en aivan
muistanut.
