* DONE Monday Mornings                                :sarjat:david_e_kelley:
CLOSED: [2013-06-15 Sat 13:24]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-06-15 Sat 13:24]
:END:

David E. Kelleyn uusi luomus on lääkärisarja kivalla twistillä.
Seuraamme Chelsea Generalin toimintaa Portland, Oregonissa. Tiivis
joukko lääkäreitä tekee parhaansa ja vain työtään. Valitettavasti
joskus kuitenkin potilaan näkemys hyvästä työstä eroaa lääkärin
vastaavasta.

Päälääkäri valvoo alaisiaan ja hoitovirheitä. Maanantaiaamuisin
kaikki kokoontuvat seuraamaan uusimpia tapauksia ja piinapenkkiin
pääsee yksi jos toinen.

Lääkärivirheiden lisäksi mukana on tietenkin aina parit
hoitotapaukset ja palaillaan aiempaan kanssa. Kelleyn tyylistä
pidän: jokainen jakso on uusi päivä maailmassa, mutta historia
painaa takana. Siis jatkuvajuonista ratkaisua hieman kevyempi
tapaus.

Sarjassa vierailee DEK-tutut, kuten *Anthony Heald* ja muita
julkimoita. Pilottijaksossa kuulin mitä mielenkiintoisimman
musiikkivalinnan pitkään aikaan: potilaan kuoltua leikkauspöydälle
pantiin etualalle soimaan Gilmour-vetoisen Pink Floydin
välisoittokappale "A New Machine" heidän vihatulta levyltään "A
Momentary Lapse of Reason", josta minä kuitenkin pidän huimasti.
Todella kiinnostava veto, josta en osaa sanoa, miten suhtautuisin
siihen. Se oli terävässä kontrastissa tavanomaisiin
pop-kappaleisiin, joten luultavasti sarjaa katsoneet ovat sankoin
joukoin nyt tutustuneet tähän unohdettuun albumiin.
