#+TITLE: Parks & Recreation
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Parks & Recreation                                     :sarjat:sitcom:
CLOSED: [2014-04-17 Thu 17:54]
:LOGBOOK:
- State "DONE"       from ""           [2014-04-17 Thu 17:54]
:END:

Pienen indianalaiskaupungin kunnallinen puisto-osasto suunnittelee
yhtä jos toista virkaintoisen Leslie Knopen johdolla. Tämä sarja on
pirteä -- mutta /hyvällä tavalla/.

[[http://www.imdb.com/title/tt1266020/][Parks & Rec]] on moderni puolituntinen, nauruton tilannekomedia.
Kirkkaisiin tähtiin kuuluvat Amy Poehler (SNL), Nick Offerman, Aubrey
Plaza ja Chris Pratt. Kaikki hienoja nimiä, jotka tekevät luontevaa ja
maalaishenkistä komediaa hyvistä lähtökohdista.

Sarjahan ammentaa paljon julkisen puolen oikuista ja sosialistisesta
byrokratiasta. Hupia riittää jopa Amerikan mantereella tähän.
Konseptihan sinänsä kääntyisi hyvin vaikka Suomeenkin: joku
pohjanmaalainen pikkukunta sopisi hyvin miljööksi siinä missä
Pawneekin.

Mukana on sellainen dokumentintapainen kerrontatapa, ja se on ollut
hyvä valinta, tarjoten muutamia uusia jippoja näyttelijöille. Sarja
huokuu eräänlaista raikkautta, jota puhtaassa maalaisilmassa on tapana
olla. Tämä lähti liikkeelle lyhyen ykköskauden kanssa hyvin
jatkuvajuonisesti, ja sekös olisi kanssa ollut erinomainen idea
jatkollekin. Kakkoskaudella siirryttiin enemmän kvantittuneeseen
meininkiin. Sarjaa taidetaan vielä toistaiseksi tehdä, tai ainakin
uusia näytetään viikoittain. 

Nyt olen menossa neljännellä kaudella, ja aistin joitakin muutoksia
tyyleissä edellisiin kolmeen nähden. Jos sama trendi jatkuu, on sarja
degeneroitumassa. Mitään yksittäistä syytä tai merkkiä degeneraatiolle
en osaa asettaa: tällä kaudella vain pelataan vähän vähemmän
dokumenttikortilla ja henkilöhahmojen terävyydet tasoittuvat ikävästi
osittain.
