#+TITLE: Parks & Recreation
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Parks & Recreation                                     :sarjat:sitcom:
CLOSED: [2014-04-17 Thu 17:54]
:LOGBOOK:
- State "DONE"       from ""           [2014-04-17 Thu 17:54]
:END:

Pienen indianalaiskaupungin kunnallinen puisto-osasto suunnittelee
yhtä jos toista virkaintoisen Leslie Knopen johdolla. Tämä sarja on
päähenkilöidensä tapaan pirteä -- mutta /hyvällä tavalla/.

[[http://www.imdb.com/title/tt1266020/][Parks & Rec]] on moderni puolituntinen, nauruton tilannekomedia. Sarjan
kirkkaisiin tähtiin kuuluvat Amy Poehler (SNL), Nick Offerman, Aubrey
Plaza ja Chris Pratt. Kaikki hienoja nimiä, jotka tekevät luontevaa ja
maalaishenkistä komediaa hyvistä lähtökohdista.

Sarjahan ammentaa paljon julkisen puolen oikuista ja sosialistisesta
byrokratiasta. Hupia riittää jopa Amerikan mantereella tähän.
Konseptihan sinänsä kääntyisi hyvin vaikka Suomeenkin: joku
pohjanmaalainen pikkukunta sopisi hyvin miljööksi siinä missä
Pawneekin.

Mukana on sellainen dokumentintapainen kerrontatapa, ja se on ollut
hyvä valinta, tarjoten muutamia uusia jippoja näyttelijöille. Sarja
huokuu eräänlaista raikkautta, jota puhtaassa maalaisilmassa on tapana
olla. Tämä lähti liikkeelle lyhyen ykköskauden kanssa hyvin merkein
jatkuvajuonisesti, ja sekös olisi kanssa ollut erinomainen idea
jatkollekin. Kakkoskaudella siirryttiin enemmän kvantittuneeseen
meininkiin, mutta tietenkin tapahtumat seuraavat toinen toisiaan
fiksusti. Sarjaa saatiinkin tehtyä kunniakkaat 7 tuotantokautta.

Nyt olen menossa neljännellä kaudella, ja aistin joitakin muutoksia
tyyleissä edellisiin kolmeen nähden. Jos sama trendi jatkuu, on sarja
degeneroitumassa. Mitään yksittäistä syytä tai merkkiä degeneraatiolle
en osaa asettaa: tällä kaudella vain pelataan vähän vähemmän
dokumenttikortilla ja henkilöhahmojen terävyydet tasoittuvat ikävästi
osittain. Onneksi nyt jälkeenpäin huomaan, että degeneraatio ei ole
valtavaa, ja vaikka tiettyjen hahmojen terävin kärki tuntuu
tylsistyvän kausien edetessä, on asia luonnollisena henkilökehityksenä
perusteltavissa. On myös mukavakin nähdä, mihin suuntaan Pawneen
pikkuväki liikkuu ajan edetessä.

Sarjan kirjoitus on erinomaista. Hahmojen motiivit, tapahtumien
kehitys, aiempien ilmiöiden callbackit ja dialogi on tehty juuri
oikein. Romanttisten tapahtumien kohdalla siirappia ei ole säästelty,
mutta jokseenkin realististen parisuhteiden takia tämän antaa
anteeksi. Sarjassa käytetään ilmeisesti improvisaatiota paljonkin
otosten välillä, tämä ilmeisesti Amyn SNL- ja UCB-taustan takia.
Monella muullakin on teatteri- ja improtaustoja takanaan, mikä on
tuntunut olevan onnistunut idea.

Viimeinen kausi on erittäin kauniisti rakennettu, ja voittaa
toteutuksessa jopa 30 Rockin vastaavan. Vaikutteet on otettu
esimerkiksi Six Feet Underin päätösjaksosta, jonka täytyy olla
eräänlainen mittapuu päätösjaksojen suhteen.
