* DONE It's Saturday Night!                                          :sarjat:
CLOSED: [2013-09-05 Thu 18:43]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-09-05 Thu 18:43]
:END:

/SNL/ eli /Saturday Night Live/ on käsite, johon Suomessa ehkä
törmätään harvemmin. Ja ne kerrat, kun siihen törmätään, nähdään
vain outoa ja kuivaa sketsihuumoria vähillä mausteilla. Ehkä näin,
mutta olen alkanut nähdä uusia ulottuvuuksia tästä hienosta
installaatiosta.

Vuodesta 1975 alkaen säännöllisesti pyörinyt sketsisarja esitetään
New Yorkista käsin livenä ja joka viikko sketsejä piristää jokin
vierastähti, eli illan /isäntä/. Sketsit ovat hyvinkin toistuvia ja
seassa silloin tällöin jotain uutta kokeilua. Sarjan mukavuus on
seurata ihmisten nousua ryysyistä rikkauksiin. Esimerkiksi Bill
Murrayn, Eddy Murphyn, Mike Myersin, Tina Feyn ja Will Ferrellin
tapaiset nimet ovat tulleet pinnalle juuri SNL:n kautta. Ja nyt
esimerkiksi sarjan pääkirjoittaja Seth Meyers pääsee jatkamaan
uraansa NBC:n myöhäisillassa Jimmy Fallonin tilalla (Fallon siirtyy
Tonight Show'hun kun Leno jää /toista/ kertaa eläkkeelle.)

Tähdet tuikkivat siis. Ja riemastuttavaa on kanssa nähdä paljon
hienoja tähtiä elokuva- ja TV-maailmasta. Hugh Laurie on
esimerkiksi oiva SNL-isäntä. Innolla odotan saavani aikaa katsoa
Jeff Bridgesin isännöimän jakson parin vuoden takaata. Onpa myös
Conan tehnyt jakson. Moni aiempi SNL:stä ponnahdusta saanut on
myös tullut vierasisännöimään muistoja virkistääkseen.

Sarja on hyvin liberaalissa hengessä tehty ja demokraatit
kukoistavat urbaanin manhattanilaismiljöön keskellä. Senkin kestää,
kun huomaa toistuvista kaavoista parhaan kaiken keskeltä:
vakiokasti on hyvin läheistä porukkaa ja koko tunnin jaksosta tulee
pitkästi sellainen "perhe koolla" -fiilinki. Ihmiset tuntuvat
selvästi tulevan ensisijaisesti viettämään hyvää aikaa keskenään ja
vasta toissijaisesti tuottamaan tv-katsojille tasokasta viihdettä.
Eipä siinä, tunnin ohjelmaan ehtii kyllä saada parit naurut
aikaiseksi. Tätä korostaa vielä ainakin nykyjaksoissa henkevä
alkumusiikin aikana tehtävä kattava listaus vakituisista ja
uusista "koeajalla" olevista nimistä. Sopivan kiireetöntä menoa ja
sopisi muuallekin.
