#+TITLE: It's Saturday Night!
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE It's Saturday Night!                                          :sarjat:
CLOSED: [2013-09-05 Thu 18:43]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-09-05 Thu 18:43]
:END:

/SNL/ eli /Saturday Night Live/ on käsite, johon Suomessa ehkä
törmätään harvemmin. Ja ne kerrat, kun siihen törmätään, nähdään
vain outoa ja kuivaa sketsihuumoria vähillä mausteilla. Ehkä näin,
mutta olen alkanut nähdä uusia ulottuvuuksia tästä hienosta
installaatiosta.

Vuodesta 1975 alkaen säännöllisesti pyörinyt sketsisarja esitetään New
Yorkista käsin livenä ja joka viikko sketsejä piristää jokin
vierastähti, eli illan /isäntä/. Sketsit ovat hyvinkin toistuvia ja
seassa silloin tällöin jotain uutta kokeilua. Sarjan mukavuus on
seurata ihmisten nousua ryysyistä rikkauksiin. Esimerkiksi Bill
Murrayn, Eddy Murphyn, Chris Rockin, Adam Sandlerin, Mike Myersin,
Tina Feyn, Amy Poehlerin ja Will Ferrellin tapaiset nimet ovat tulleet
pinnalle juuri SNL:n kautta. Ja nyt esimerkiksi sarjan pääkirjoittaja
(kausilla ~35-39) Seth Meyers pääsee jatkamaan uraansa NBC:n
myöhäisillassa Jimmy Fallonin tilalla (Fallon siirtyy Tonight Show'hun
kun Leno jää /toista/ kertaa eläkkeelle.)

Tähdet tuikkivat siis. Ja riemastuttavaa on kanssa nähdä paljon
hienoja tähtiä elokuva- ja TV-maailmasta. Hugh Laurie on
esimerkiksi oiva SNL-isäntä. Innolla odotan saavani aikaa katsoa
Jeff Bridgesin isännöimän jakson parin vuoden takaata. Onpa myös
Conan tehnyt jakson. Moni aiempi SNL:stä ponnahdusta saanut on
myös tullut vierasisännöimään muistoja virkistääkseen.

Sarja on hyvin liberaalissa hengessä tehty ja demokraatit
kukoistavat urbaanin manhattanilaismiljöön keskellä. Senkin kestää,
kun huomaa toistuvista kaavoista parhaan kaiken keskeltä:
vakiokasti on hyvin läheistä porukkaa ja koko tunnin jaksosta tulee
pitkästi sellainen "perhe koolla" -fiilinki. Ihmiset tuntuvat
selvästi tulevan ensisijaisesti viettämään hyvää aikaa keskenään ja
vasta toissijaisesti tuottamaan tv-katsojille tasokasta viihdettä.
Eipä siinä, tunnin ohjelmaan ehtii kyllä saada parit naurut
aikaiseksi. Tätä korostaa vielä ainakin nykyjaksoissa henkevä
alkumusiikin aikana tehtävä kattava listaus vakituisista ja
uusista "koeajalla" olevista nimistä. Sopivan kiireetöntä menoa ja
sopisi muuallekin.

** Kaudet 30-39

Kaudet 30-39 kattavat ajan syksyltä 2004 kevääseen 2014. En ole
kaikkea päässyt näkemään, mutta näiden jaksojen parissa minä nyt
kuitenkin tutustuin sarjaan sisälle, ja siitä syystä tuskin osaan
odottaa yhtään parempaakaan. Sarja on vakaasti hyvä, ja helmiä on
kaikkialla. Kaudella 38 totesin jonkinlaisen selvän putouksen tasossa,
mutta siitäkin selvittiin kyllä kauden loppuun mennessä.

Alkupäässä "kolmikymppisiä" nähdään Tina & Amy /Weekend Update/
-pöydän takana ja Tina on sarjan pääkirjoittaja samalla. Tina lähtee
kai kaudella 32 tai vastaavasti ja Seth Meyers astuu Amyn kaveriksi
WU-pöytään ja samalla sarjan pääkirjoittajaksi. Sekin osoittautui
hyväksi valinnaksi kaikkinensa. Nyt jänskättääkin, että miten seuraava
pääkirjoittaja suoriutuu tehtävistään Sethin lähtiessä 39. kauden
loppupuolella uuteen työhönsä.

** Miten päästä sisään?

SNL:n tapainen ohjelma voi satunnaisella katselmoinnilla tuntua aika
ankealta ja kuivalta. Huono tai vähäisellä huumorilla varustettu
sketsi saattaa helposti antaa huonon maun koko jaksosta. Näin
totisesti minusta ainakin oli. Sisään kuitenkin pääsee vahingossa
samalla tavalla kuin TV:n tyypillisiin puheohjelmiin ja vastaaviin:
tuttuja naamoja seuraamalla.

Tarkastele Wikipediasta tai jostain kunnollisesta lähteestä
tuoreehkojen SNL-kausien vierailijanimiä ja valitse mieleisiä
katsottavaksi. Jos katsot vielä useamman, niin alat luultavasti nähdä
kuvioita ja säännönmukaisuutta menossa. Opit arvostamaan hyviä juttuja
ja sivuuttamaan huonompia. Huonoja sketsejä ei enää näekään samalla
tavalla kun osaa poimia vain ne hyvät mieleensä. Tai sitten et; SNL ei
sitten ole sinulle.
