* DONE The Newsroom                                                  :sarjat:
CLOSED: [2013-02-07 Thu 11:07]

Kiinnostava sarja Jeff Danielsin johdolla kertoo uutistoimistosta,
joka kilpailun kiristyessä reformoi tyylinsä kokonaan. Sarja nappaa
oikeita uutisia parin vuoden takaa aihepiiriinsä ja tekee yleisesti
ottaen hyvää HBO-laatua. Olen neljä jaksoa katsonut ensimmäisestä
10 jakson kaudesta. (Nyttemmin koko ensimmäisen kauden.) Uutta on
tulossa, sillä juuri tarkastin IMDB:stä että toista kautta on jo
kaksi jaksoa ulostautunut.

Newsroomin käsikirjoitus on oivaa, vaikka onkin poliittisesti
värittynyttä. Kunnon taiteissahan ei minusta politiikalle ole
sijaa. Mutta jos tehdään politiikasta taidetta, on se kai
pakollinen paha... Kirjoitus on originaalia, ja paikkaa paljon. Ei
sillä, että paikattavaa olisi kamalasti. Näyttelijöiden työskentely
on ihan hyvää, vaikka aivan vakavimmasta työstä ei puhutakaan. Jeff
Daniels ja Emily Mortimer toimivat hyvin yhdessä kyllä. Mukava
/feelgood/ jää katsomisen jälkeen pyörimään ilmaan. Lennokas
musiikki varmasti tekee osansa.

Päivitetty 2013-03-29.
