#+TITLE: The Unit
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE The Unit                                                      :sarjat:
CLOSED: [2013-04-07 Sun 19:28]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-04-07 Sun 19:28]
:END:

Tämä supermainio [[http://www.imdb.com/title/tt0460690][sarja]] kertoo amerikkalaisesta erikoisjoukkueesta
tekemässä "black opseja" armeijan piikkiin ympäri maailmaa.
Tarkastelussa on sekä nelihenkinen tiimi että heidän vaimonsa ja
heilansa sotilasalueen asutuksessa. Työ on salaista, ja perheetkin
on pidettävä turvassa.

Viime torstaina uppouduin viimeistä kertaa Snake Doctorin, Dirt
Diverin, Betty Bluen ja Cool Breezen, (sekä avustamassa Dogpatch,
Whiplash ja Red Cap), seurassa kun sarja sitten loppui. Neljä upeaa
kautta ovat täynnä hektistä ja erittäin hyvin tuotettua äksöniä.
Käsikirjoitus on rehellistä ja luontevaa, toiminta on näpäkkää ja
nämä meidän pikku-commandot toimivat kuuliaisesti.

Dennis Haysbert ja Robert Patrick isompina tähtinä ja koko
(modernimpi) tiimi on erittäin kelvollisesti valittuja
näyttelijöitä täynnä. Tätä sarjaa katsoisi mielellään lisää. Vaikka
suuret kuviot olivat hieman väsyneitä, jokaisen jakson oma tehtävä
on aina niin hyvin tehtyä, ettei kyllästymään voi mitenkään päästä.

Superlämpimät suosittelut.
