#+TITLE: The Unit
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE The Unit                                                      :sarjat:
CLOSED: [2013-04-07 Sun 19:28]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-04-07 Sun 19:28]
:END:

Tämä supermainio [[http://www.imdb.com/title/tt0460690][sarja]] kertoo amerikkalaisesta erikoisjoukkueesta
tekemässä "black opseja" armeijan piikkiin ympäri maailmaa.
Tarkastelussa on sekä nelihenkinen tiimi että heidän vaimonsa ja
heilansa sotilasalueen asutuksessa. Työ on salaista, ja perheetkin
on pidettävä turvassa.

Tehtävät ovat tyypillisiä black ops / delta -missioita milloin
missäkin. Joskus ollaan sattumalta oikeassa paikassa oikeaan aikaan,
joskus kaikki on suunniteltu kaukaa etukäteen. Koulujen ja
lentokoneiden kaappaamisia ollaan purkamassa, panttivankitilanteita
milloin missäkin. Joskus ollaan jonkun kehitysmaan sotatantereella
tarjoamassa taktista tukea diplomatiasyistä. Jossain huutokaupataan
ydinkärkiä teroille, The Unit on paikalla.

Viime torstaina uppouduin viimeistä kertaa Snake Doctorin, Dirt
Diverin, Betty Bluen ja Cool Breezen, (sekä avustamassa Dogpatch,
Whiplash ja Red Cap), seurassa kun sarja sitten loppui. Neljä upeaa
kautta ovat täynnä hektistä ja erittäin hyvin tuotettua äksöniä.
Käsikirjoitus on rehellistä ja luontevaa, toiminta on näpäkkää ja
nämä meidän pikku-commandot toimivat kuuliaisesti.

Dennis Haysbert ja Robert Patrick isompina tähtinä ja koko
(modernimpi) tiimi on erittäin kelvollisesti valittuja
näyttelijöitä täynnä. Tätä sarjaa katsoisi mielellään lisää. Vaikka
suuret kuviot olivat hieman väsyneitä, jokaisen jakson oma tehtävä
on aina niin hyvin tehtyä, ettei kyllästymään voi mitenkään päästä.
Superlämpimät suosittelut.

** Band of Brothers

Olen nyt katsomassa Band of Brothers -minisarjaa ensimmäistä kertaa
läpi. Todella kehuttu ja tuotannollisesti hyvin pätevä sarja ei ole
rikkonut mitään hypeä itsestään, ja jokainen jakso on ollut nautintoa
nähdä. Mikä kuitenkin tärkeintä tämän postauksen puitteissa: The Unit
kestää suoraa vertailua BoBiin nähden. Toki Unitissa mennään välillä
vähän oudommissa piireissä, mutta selvästi enemmän kuin 10 jaksoa
Unittia on yhtä korkeatasoista meininkiä kuin BoB. Jos tämä ei käy
suosittelusta, niin sitten et ole lainkaan sotatoimintasarjoihin
kallellaan.
