#+TITLE: The Newsroom
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE The Newsroom                                                  :sarjat:
CLOSED: [2013-02-07 Thu 11:07]

Kiinnostava sarja Jeff Danielsin johdolla kertoo uutistoimistosta,
joka kilpailun kiristyessä reformoi tyylinsä kokonaan. Sarja nappaa
oikeita uutisia parin vuoden takaa aihepiiriinsä ja tekee yleisesti
ottaen hyvää HBO-laatua. Kaksi näytettyä kautta nähneenä pidän
kovasti, ja odottelen innolla kolmatta ja samalla viimeistä kautta.

Tavallisesti en nauti taiteen ja politiikan sekoittamisesta, sillä
politiikka myrkyttää taiteellisuuden helposti. Uutishuoneessa
politiikasta ei voi kuitenkaan välttyä, ja Newsroomissa sitä on sitten
käsiteltävä, ja käsitelläänkin. Tapa, miten asioita sitten puidaan, on
onnistunut, ja voin helposti hyväksyä kirjoituksen. Sarjan luonut
Aaron Sorkin on selvästi puntaroinut hyvän ja neutraalin alueen sieltä
keskeltä ratkaistaakseen tämän probleeman.

Kirjoitus on originaalia, ja paikkaa paljon. Ei sillä, että
paikattavaa olisi kamalasti. Näyttelijöiden työskentely on ihan hyvää,
vaikka aivan vakavimmasta työstä ei voida puhua. Jeff Daniels ja Emily
Mortimer toimivat hyvin yhdessä kyllä. Mukava /feelgood/ jää
katsomisen jälkeen pyörimään ilmaan. Lennokas musiikki varmasti tekee
osansa. Se on se Manhattanin taika taustalla.
