#+TITLE: The Newsroom
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE The Newsroom                                                  :sarjat:
CLOSED: [2013-02-07 Thu 11:07]

Kiinnostava sarja Jeff Danielsin johdolla kertoo uutistoimistosta,
joka kilpailun kiristyessä reformoi tyylinsä kokonaan. Sarja nappaa
oikeita uutisia parin vuoden takaa aihepiiriinsä ja tekee yleisesti
ottaen hyvää HBO-laatua. Kaksi näytettyä kautta nähneenä pidän
kovasti, ja odottelen innolla kolmatta ja samalla viimeistä kautta.

Tyypillisesti en nauti taiteen ja politiikan sekoittamisesta, sillä
politiikka myrkyttää taiteellisuuden helposti. Uutishuoneessa
politiikalta ei voi kuitenkaan välttyä, ja Newsroomissa sitä on sitten
käsiteltävä, ja käsitelläänkin. Aaron Sorkin kirjoittaa käsiksiä
väkevästi, mutta hänen omat näkemykset paistavat läpi dialogista ja
käytetyistä argumenteista. Hän maalaa Jeff Danielsin hahmon
liberaalina republikaanina, kuuluen siihen koulukuntaan, joka uskoo,
että todellisuudella on vasemmistolainen bias. Koska sarjassa käytetyt
argumentit on fakta- ja tilastopainotteista, selvä enemmistö katsojista
nauttinee kyllä kokonaisuudesta.

Kirjoitus on originaalia, ja paikkaa paljon. Ei sillä, että
paikattavaa olisi kamalasti. Näyttelijöiden työskentely on ihan hyvää,
vaikka aivan vakavimmasta työstä ei voida puhua. Jeff Daniels ja Emily
Mortimer toimivat hyvin yhdessä kyllä. Mukava /feelgood/ jää
katsomisen jälkeen pyörimään ilmaan. Lennokas musiikki varmasti tekee
osansa. Se on se Manhattanin taika taustalla.
