#+TITLE: The X-Files
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE The X-Files                                                   :sarjat:
CLOSED: [2014-03-01 Sat 17:08]
:LOGBOOK:
- State "DONE"       from ""           [2014-03-01 Sat 17:08]
:END:

Aloitin torstaina X-Filesin uudelleenkatsomisurakan. X-Files, tai
suomalaisittain /Mappi Ö/, on tietysti tämä suurin 90-luvun
instituutio TV-maailmassa, mitä on. Twin Peaks ensin 90-luvun alussa
ja sitten X-Files koko loppuvuosikymmenen. Näemme Toivo Mulperia,
Taina Kultsista ja Pertti Nahkalaa hamaan tulevaisuuteen asti. Alkava
katsontakierros on minulle kolmas, ja edelliskerrasta on jo aikaa.

Ensijaksot määrittelevät niin paljon X-Filesiä ja heti pilottijaksossa
ainakin pannaan rytisten kaikki myöhemmin tutuiksi syntyvät elementit
kovaan käyttöön. Salaliittoteoriat ovat oma suosikkini ja sarjan
mytologiajaksot hunajaisinta mahlaa. Täytepätkät ovat hitti-tai-huti
-tyylisiä. Sarjan nokkela käsikirjoitus ja sankareidemme kemia auttaa
kyllä pitämään tason yhtenäisenä.

Muistan kyllä sarjan vaiheista niin monia upeita "Monster of the week"
-jaksoja, joissa viihtyy silkan hulluttelun ja päheän kirjoituksen
ansiosta. Doppelgängereitä, sirkuskääpiöitä ja vampyyreja. Erityisesti
jakso nimeltä [[http://en.wikipedia.org/wiki/Bad_Blood_(The_X-Files)][Bad Blood]] tykitti kovaa. Ensimmäinen jakso, jonka
katsoin /Filesiä/, oli [[http://en.wikipedia.org/wiki/D.P.O.][D.P.O.]] kolmannelta kaudelta. Kyllähän se työn
taso ja laatu säväytti kovasti. Toistaiseksi paras jakso koko sarjasta
on ollut [[http://en.wikipedia.org/wiki/Little_Green_Men_(The_X-Files)][Little Green Men]], kakkoskauden avaava mytologiatykitys.
Katsotaan, tuleeko uusia suosikkeja matkan varrella. Klassiset
"junajaksot" (alkaen [[http://en.wikipedia.org/wiki/Nisei_(The_X-Files)][Nisei]]:stä) ja muut vastaavat, miksei vaikka
pilottijakso tai toisena tuleva [[http://en.wikipedia.org/wiki/Deep_Throat_(The_X-Files_episode)][Deep Throat]] voisivat olla hyvinkin
top-listoilla. Ne kaksi olen katsonut tätä urakkaa eteenpäin, ja
todella hengästyttävää settiä ovat olleet.

X-Files on inspiroinut niin monia myöhempiä sarjoja samalla tavalla
kuin aikaisemmat esikuvat inspiroivat X-Filesiä. Pääpuolin elokuva [[http://www.imdb.com/title/tt0074119/][All
the President's Men]] mutta myös Twin Peaks ja muut.

Jotkut sanovat, että X-Files on auttamattoman vanhentunut, mutta minun
on sitä vaikea nähdä. Salaliitot eivät ole loppuneet, ja tarinat on
tietysti kirjoitettu melkein ajattomaksi. Pienet vihreät miehet eivät
mene muodista noin vain. X-Filesin teemamusiikki (Mark Snow'n
käsialaa) on varmasti kaikkien aikojen paras tv-sarjamusiikki. Sarjan
ambienssissa on muutenkin paljon enemmän musiikkia kuin nykypäivän
kyhäelmissä, ja minä ainakin pidän siitä.

Lisäksi on aina piristävä nähdä entisaikain ja nykyisiäkin tähtiä
pikkuosissa. Esimerkiksi Seth Green esitti teiniä heti sarjan alussa.
Ja muita on luvassa, se tästä sarjasta tiedetään!

** Kausi X

Hieman yllättäen sarja sai jatkoa kaikkien näiden vuosien jälkeen.
Kuusiosainen kausi on järjestyksessään kymmenes, ja on
mielenkiintoista nähdä, miten sarja istuu nykyaikaisen sarjan
viitekehyksessä. Ensimmäisen jakson perusteella hankala sanoa vielä
mitään. Nuoruuden vimmaa ei ainakaan jaksossa ole samaan tapaan kuin
kuudennella kaudella.

Niin, sarjan katsomisrundi, jonka aloitin helmikuun lopussa 2014, on
edennyt tänä kahtena vuonna seitsemännen kauden alkuun, eli sanotaanko
että 6,5 kautta kahdessa vuodessa. Aina torstaisin 1-2 jaksoa, se on
ihan hyvä tahti.

Yllättäen eniten homma kanitteli kausilla 2-3, joiden piti olla
kaikkien mielestä niitä parempia kausia. Tuli pidettyä taukoa
katsomisesta. Kaudesta 4 eteenpäin on taas ollut kivempaa. Nyt
tietysti seitsemäs kausi on täynnä aika villiä kamaa, on X-Copsia,
First Person Shooteria ja Hollywood AD:ta. Kuudes kausi oli tiukkaa
kamaa myös mytologian kannalta. Tuntuu kuin koko mysteeri tuli
purettua siellä One Son / Two Fathers -jaksokaksikon merkeissä, ja
kaikki siitä eteenpäin on sen kertaamista!
