#+TITLE: Vuosi filmikuvaamista
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Vuosi filmikuvaamista                                   :kamera:filmi:
CLOSED: [2024-09-22 Sun 11:07]
:LOGBOOK:
- State "DONE"       from              [2024-09-22 Sun 11:07]
:END:

Syyskuussa 2023 filmikipinä syttyi liekiksi. Mitä vuodessa ehti
tapahtua?

#+CAPTION: Näistä sitä lähdettiin vuosi sitten. Kehitys tuotti raitaa. Ultramax 400.
[[./kuvat/filmi1v/2023-10-07 (Sat) 12-12-40.jpg]]

#+CAPTION: Näistä sitä lähdettiin vuosi sitten. Kehitys tuotti raitaa. Varhainen low-fi-skannaus ennen kuin oli oikea systeemi. Ultramax 400.
[[./kuvat/filmi1v/2023-10-07 (Sat) 13-56-38.jpg]]

** Luomistarina

Siihen aikaan olin ollut sen puolisen vuotta työttömänä, mutta
rahahanat menojen suhteen olivat vielä suhteellisen auki. Valokuvaus
oli harrastuksenani yleisesti hiljentynyt aika vähiin. Tiesin, että
filmi tai mikään muukaan kameralaite ei elvyttäisi harrastusta...
mutta siitä huolimatta päätin nyt mennä siihen. Järkeä ei konsultoida
näissä asioissa.

Suunnitelma oli tehdä hyvin pieni ja rajoitettu kokeilu: yksi halpa
runko, jolle olisi jo linssit entuudestaan. Kolme rullaa filmiä ja
niille kehitykset. Kokonaisuutena tämä maksaisi satasen pintaan ja
voisin viettää syyskautta sitten rauhassa fiilistellen filmin kanssa.

#+CAPTION: Hyviä syysmaisemia ja onnistumisia. Ultramax 400
[[./kuvat/filmi1v/2023-10-07 (Sat) 13-44-12.jpg]]

No, vähemmän yllättäen mopo lähti käsistä lähestulkoon heti portilla.
Yhden edullisen (edullisuus on minulle suhteellinen käsite, tällä
kertaa se tarkoitti 70 euroa) kamerarungon sijaan ostin kolme
edullista runkoa (80, 70, ja 30 euroa). Kolme rullaa filmiä
kehityksineen muuttui syys-lokakuun aikana joksikin 30 rullaksi (!).
Labrakehitykset peruin ja sen sijaan ostin kotikehityskitin
kemikaaleineen ja kalliine skannaustyökaluineen.

Rahaa upposi äkkiä puolisen tonnia tähän pieneen kokeiluun.
Kuherruskuukaudenkaan aikana en kuitenkaan valottanut emulsiota ihan
jatkuvalla syötöllä. Olin säästeliäs ja tarkka valottaja. 36 ruudun
rullat kestivät (ja kestävät ajoittain edelleenkin) tuskallisen
pitkään ennen kuin ne 'saa' kehittää.

#+CAPTION: Hyviä syysmaisemia ja onnistumisia. Ultramax 400
[[./kuvat/filmi1v/2023-10-12 (Thu) 12-28-19.jpg]]

#+CAPTION: Hyviä syysmaisemia ja onnistumisia. Kallis vintagefilmi Superia 100.
[[./kuvat/filmi1v/2023-10-21 (Sat) 18-13-36.jpg]]

Mitä kotikehitykseen tulee, epäonnistumisia ei tullut, vaikka
värikehitys on vielä käsissäni todella 'low fidelity', monenlaisten
värivirheiden kanssa.

Siinä oli onnistumisen makua ja itse tehtynä myös tekemisen makua.
Harrastus oli saanut hetkellisesti uutta pontta alleen, kuten
odotettuakin.

** Sekoilu seestyy

Olipa laitteet mitä tahansa, syksyn muuttuessa talveksi kuvaustahti
hiljeni, kuten tapahtuu joka vuosi.

Kuitenkin tältä kaudelta minulla on käsissäni kaksi erinomaista rullaa
kuvattua filmiä, hyviä onnistumisia. Mustavalkoista Ilford Kentmere
400 -filmiä ja huippurakeista Ilford Delta 3200 -tavaraa. Nopeaa
tavaraa kumpikin. Rae ei haittaa ja ylimääräinen nopeus on aina
tervetullut. Filmin kanssa voit periaatteessa aina ylivalottaa jos et
tarvitse kaikkea vauhtia.

#+CAPTION: Talvikauden onnistumisia ja parhaimpia rullia. Kentmere 400.
[[./kuvat/filmi1v/2023-11-05 (Sun) 18-09-01.jpg]]

#+CAPTION: Talvikauden onnistumisia ja parhaimpia rullia. Delta 3200.
[[./kuvat/filmi1v/2024-04-28 (Sun) 14-29-14.jpg]]

Digikuvaus käytännössä loppui kuin seinään kun filmivillitys alkoi.
Fiilis oli että jos kuva ei ole filmille niin se ei ole ottamisen
arvoinen. Tämä siis näin lähimatkailussa.

Kun kävin Japanissa tammikuussa, oli ilmiselvää alusta alkaen että se
tehdään digillä. Matka oli tietenkin erittäin tuottoisa ja meni kuusi
kuukautta saada kaikki diginegatiivit läpikäytyä. Pidetään tämä
mielessä. (A)

** Kevään tuulia

Pitkän talven jälkeen päästiin viimein kevään valoon. Kirsikankukinnan
taltiointi filmille oli odotettu tapahtuma, ja hyvä motivaattori käydä
kirsikkakierroksilla kaupungilla.

Laitoin kameraan premiumiksi kokemaani japanilaista nyrkkipajan Washi
X -värifilmiä. Joitain perustyhmiä valotuksia tuli tehtyä.

Mokasin kehityksen kuitenkin totaalisesti (ensimmäistä kertaa) ja
filmi valmistui typötyhjänä. Syy oli potenssin menettänyt kehitysaine,
joka ei tehnyt filmille mitään. Hiljalleen kuvaavalle näiden
kemikaalien lyhyt hyllyaika on isoin harmi tässä koko hommassa.

En lannistunut tästä epäonnistumisesta, vaan latasin oitis kameraan
toisen rullan Washi X:ää ja sen jälkeen Santacolor 100 -filmiä. Näiden
kehitys meni 100% nappiin ja olivat myös sisällöltäänkin rullina ihan
asiallisia.

#+CAPTION: Kesäkuuta Hyvinkäällä. Santacolor 100.
[[./kuvat/filmi1v/2024-07-12 (Fri) 17-36-06.jpg]]

** Kesästä tähän hetkeen

Asioita piristi huomattavasti töiden saanti. Kaikkea muuta paitsi
valokuvaamista, siis. Juhannuksen jälkeen aloitetut työt
ymmärrettävästi löivät jarruja kaikelle muulle harrastamiselle.
Valokuvaus, joka on ollut jo muutenkin hiljaista, sai ensimmäisenä
ottaa takapakkia.

Värifilmin skannailu ja värien kuosiinsaaminen, joka on vaikea
taiteenlaji, sai uutta harjoitusta kesällä. Pidetään tämä ajatus! (B)

Hiljaisten kotoilusesonkien välissä tehdyt reissut kotimaassa ovat nyt
ihan viimeaikoina räjähtäneet kuvausmäärien suhteen. Alan tällä
hetkellä ottaa kuvia filmille kuin se olisi ilmaista kuin digi. Täysi
rulla Kodak Goldia meni kuudessa tunnissa! Ennenkuulumatonta minulle.
Seuraavaksi ladattu Ultramax ei sekään kestänyt kuin vuorokauden.

#+CAPTION: Kesäkuuta Helsingissä. Santacolor 100(?)
[[./kuvat/filmi1v/2024-07-12 (Fri) 17-38-37.jpg]]

** Vuotta myöhemmin: missä ollaan nyt

Olen pidättäytynyt laitehankinnoista, mikä on tietenkin aina hyvä.
Mutta vietänkö nyt jonkinlaista "paluu todellisuuteen" -kautta filmin
suhteen?

Palataan kohtaan (A) aiempaa: filmikuvien kehittely on sinänsä
yksinkertaista mutta paljoa kuville ei voi aina tehdä ennen kuin ne
hajoavat käsiin. Ulkomaanreissun digikuvat sen sijaan, voi veljet.
Uskomaton joustavuus ja tietenkin korkea fideliteetti myös filmiin
verrattuna. Pimiötyöskentelyn ilo näiden digikuvien kanssa on selkeä
erävoitto digin puoleen, luonnollisesti.

#+CAPTION: Tallinna kesäkuun alussa. Washi X.
[[./kuvat/filmi1v/2024-07-12 (Fri) 17-43-00.jpg]]

Vastavuoroisesti palataan kesän tuoreeseen kehittymiseeni värifilmin
kehityksen kanssa kohdasta (B): tämä ei nyt ollut ihan uutisia mutta
printtifilmi on erittäin joustava media, jonka voi loppupeleissä
digiskannista käsitellä pitkälti haluamaansa suuntaan. Iso osa
värifilmin taiasta ropisee pois, jos voin ottaa jonkun filmin X ja
toisen filmin Y ja kehittää niistä pitkälti samannäköisiä. Onko tässä
sittenkään mieltä? Ostin premiumfilmejä vuosi sitten sillä ajatuksella
että niiden 'ominaislook' olisi jotain, jota ei digillä voi toistaa.
Nyt se idea on haastettu.

Edellisestä kehityssesiostakin on kulunut taas kuukausia ja alan
pelätä kemikaalien laadun puolesta. Kynnys kehittää kasvaa päivä
päivältä, plus aloittamisen laiskuus. Keväinen epäonnistuminen
kummittelee takaraivossa.

Olisiko kotikehityksen sijaan aika vain dumpata rullat labraan
kehitettäväksi? Yksi murheenkryyni vähemmäksi. Skannaisin ja
värikäsittelisin itse kuitenkin. Omalla verkkaisella kuvaustahdillani
olen laskenut, että labra- ja kotikehitys maksavat kutakuinkin saman,
koska niillä kemikaaleilla on se mainittu parin kuukauden käyttöikä.

(Tottakai voisin kuvailla filmiä ja keräillä sitä jääkaapin nurkkaan
ja kehitellä isot pinot filmiä kerralla vastasotkettuihin
kemikaaleihin niin saisin luotettavaa laatua. Mutta silloin kuvia
pitäisi odotella pitkä tovi, ja rahallinen säästö olisi vain kympin,
kaksi, vuositasolla.)

Olen nyt loppukesästä lähtien alkanut kantaa enemmän digiä mukanani.
Hyvät ja luotettavat kehitykset (per kohta (A)) painavat hieman
vaakakupissa. Ensimmäinen filmivillityksen aalto on ehkä ohi. Onko
koko filmikokeilun aika?

#+CAPTION: Tallinna kesäkuun alussa. Washi X.
[[./kuvat/filmi1v/2024-07-12 (Fri) 17-45-08.jpg]]

** Vuoden aikana opittua

Nopeat filmit ovat mieleeni. Kentmere 400 valottuu tosi nätisti
1600-herkkyyksisenä. Delta 3200 on päheää tavaraa sekin, vaikka sen
rae onkin jo aikamoista puuroa.

Värifilmissä 400-nopeuksiset ovat tosi bueno. Pidän maltillisesta
rakeesta suhteessa nopeuteen.

Kolmijalka ilman lankalaukaisinta: turhake. Pitää yrittää muistaa aina
pakata kumpikin mukaan, ei kolmijalkaa yksinään.

Keskiformaatti saattoi tuntua hyvältä yhteen aikaan, mutta kaluston
ylenpalttinen paino ei viehätä yhtään. Yksi probleema filmissä
muutenkin on tämä paino.

Pohdintaa: vuoden hienoimmat kokemukset ovat olleet
täysautomaattisella muovilelulla (29 euroa, Nikon F70) otetut
mustavalkokuvat. Otanko vihjeestä vaarin? Hyvä valotusmittaus kameraan
rakennettuna on asia, jonka digikuvaajat ovat ottaneet käytännössä
aina itsestäänselvyytenä.

Haluaisin ehkä samanlaisen täysautomaattisen Nikonin, mutta jos se
olisi hieman pienempi ja vähemmän muovinen kuin tuo F70 niin olisi
kiva. Olen vähän pohtinut, että elpyisikö filmikuvaus vähän, jos
ostaisin jonkun kivan mittaetsinpokkarin (esimerkiksi Canonet 19).
Sykli uusiutuu...

#+CAPTION: Tallinna kesäkuun alussa. Washi X.
[[./kuvat/filmi1v/2024-07-12 (Fri) 17-45-36.jpg]]

Liitetyt kuvat ovat muutamia valintoja matkan varrelta. Osa on ihan
ensimmäiseltä rullalta ja viimeisimmät, no, viimeisimmiltä
skannatuilta rullilta juhannuksen tienoilta. Kaikkein tuoreimmat
filmit on vielä kehittämättä.
