#+TITLE: Vuosi filmikuvaamista
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* Vuosi filmikuvaamista                                        :kamera:filmi:

Siitä tuleekin jo vuosi kun innostuin hankkimaan Nikon F -systeemiini
täydennystä filmirunkopuolelta.

Ostin innostuksissani paljon roinaa vuosi sitten syyskuussa. Kolme
filmirunkoa: Nikkormat FTn, Nikkormat FT2 ja Nikon F70 -halparunko.
Itseasiassa kaikki näistä ovat halparunkoja, mutta Nikkormatit ovat
täysiverisiä rautaesineitä, joita Nikon teki 70-luvulla "off brand"
-tyyliin houkutellakseen systeemiin tulijoita edullisilla kameroilla.
Nikon F70 on sitten muovinen hilavitkutin hienoilla (ja toimivilla)
automatiikoilla 90-luvulta.

Kaikki näistä minulla edelleen on, mutta FTn on nähnyt vähiten
käyttöä. FT2 ja F70 ovat taasen käytännössä kuluneen 12 kuukauden
aikana eniten käytettyjä kameroitani.

12 kuukauden aikana olen ehtinyt laittaa n. 19 rullaa kinofilmiä
kameroiden läpi. Osa filmeistä on 24 kuvan mittaisia, muutama hassu on
27 kuvaa ja loput 36. Jos vaikka arvioimme keskimääräisen filmin
pituudeksi 32 kuvaa niin filmikuvia olen ottanut 600 kappaletta. Tämä
on aika vähän verrattuna niihin lukemiin, joita digikuvan hulluina
vuosina (2019) vedin. 600 kuvaa saattoi tulla mittariin parin tunnin
kävelyn aikana, jos oikein huonosti kävi! Sen minkä kentällä voittaa
niin pimiössä häviää.

Kotioloissa ja tutuissa maisemissa filmi on syrjäyttänyt
digikuvaamisen pitkälti kokonaan. Ulkomaanreissuilla olen suosiolla
mennyt digillä, enkä ole sinänsä kaivannut filmikameran haasteita ja
laitteiden painoa.

Nyt hiljan viimeisimmällä kotimaan matkalla päätin ottaa myös pitkät
sarjat kuvia digi-Nikonilla.

** Fiilistely

Paljon kirjoitan täällä siitä, miten digiä on nautinnollinen kuvata
(koska digi ei ole aina digi: tapausesimerkit Leica M ja Nikon Df),
niin viimeisen 12 kuukauden aikana on ollut paljon sitä fiilistä että
jos kuvaa en ota filmille niin sitä ei tarvitse ottaa.

Lisäksi kun olen taas palkkatöissä pienet kustannukset filmirullien ja
kehityksen (/kehitysaineiden) suhteen eivät pitäisi painaa
vaakakupissa.

Ehkä vain suon itselleni pienen hengähdystauon filmin haasteellisista
puolista ja keskityn hyviin puoliin, vaikka se vähän maksaisi.
Ostaisin pari rullaa kivaa värifilkkaa, joihin kehitykset labrassa.
Ehkä soma pokkarikamera, jota voisi kanniskella talven pimeillä
taskussaan silloin "kun ei halua kantaa kameraa mukanaan".

** Skannailu ja kehittely

Olen kehittynyt tässä hommassa mielekkäästi paremmaksi, mutta vaikeata
se silti on. Rajallisempi dynaamisuus ja muut seikat tekevät asioista
tavallaan helpompia, tavallaan vaikeampia. Helppous tulee lähinnä
siitä että suosiolla unohdan kaikenlaiset hienot kikkailut mitä digin
kanssa tekisin.

** Ehtyykö innostus

Moni valokuvaaja on löytänyt filmistä uuden muusan, joka on puhaltanut
harrastukseen hehkua. Itsekin toki nautin aluksi filmikuvaamisen
tuomista aspekteista, kuvaamisesta ilman liiallisia tietokoneapuja.

Mutta olin skeptinen hurmoksen pysyvyydestä, ja nyt ollaan vähän
menossa takaisin siihen että arvostan digikuvien käsiteltävyyttä ja
nopeutta ja luotettavuutta.

Alkujaan oli iso innostus kokeilla erilaisia filmejä ja nauttia
retroväreistä ilman digikikkasteluita. Tässä todellisuus tuli kovasti
vastaan: värifilmin käsittelyn jäljiltä kuva voi olla ihan mitä vain
ja viimekädessä digiskannin käsittelyssä sille on melkeinpä pakko
tehdä jotain säätöä. Eli tämä fiini aspekti erilaisten filmien
pyörittelystä kaatui ja kaikki tähän liittyvä rämpiminen (värien
tuunaaminen, skannausten virittely) kaikki tietää erävoittoja
digileirin puolesta.

** Filmin kehittäminen

Labrakehitykset maksavat luokkaa 8-12 euroa per rulla. Minun
verkkaisella kuvaustahdillani jos haluan kehittää kuvat kohtuuripeästi
rullan valmistuttua niin labrakehitykset ja oma kehittäminen menee
itseasiassa pitkälti tasoihin kustannuksiltaan.

Laiskuus aloittaa, epävarmuus kemikaalien eheydestä ja epätasaisesti
kehittyvät rullat alkavat kovasti puoltaa ajatusta siitä että lähtisi
jatkossa kehityttämään kaiken labrassa. Mutta siinä tapauksessa tuli
ostettua hyvät laitteet turhaan. (No, kehitysinvestoinnit eivät olleet
kuin 50 euron luokkaa, kemikaalit erikseen.)

Toinen vaihtoehto on vain keräillä filmejä jääkaappiin ja sitten
kehitellä nopeassa ajassa isompi satsi pois. Kemikaalien luotettavuus
ja pieni säästö olisi saavutettavissa näin. Labrassa kehittävät kyllä
värifilmit ilmiömäisesti paremmin kuin mitä olen itse vielä kertaakaan
onnistunut. Mutta en kiellä, etteikö siitä tulisi pientä tyydytystä
kun tekee itse vaikka vain 75% laadulla.

** Laitteet kunnossa

Muutama filmiin liittyvä harmittelu liittyy osittain eniten käyttämäni
kameran eli Nikkormat FT2:n aspekteihin. Kameran filmilatausmekanismi
on varmasti aika standardi mutta se jättää usein epävarmaksi sen että
tuliko filmi ladattua oikein, lähtikö se kelautumaan. Tämä on varmasti
oman harjoituksen puutetta, mutta ainahan sitä pätevä tekijä syyttää
laitteitaan.

Vohoi, laitekuumettako? Filmin suhteen laitekuume on omanlaisensa suo.
Moni vehje on digiä rutkasti edullisempi, mutta kuitenkin hehkeimpien
trendikameroiden raketoivat hinnat laittavat vähän harmittamaan.

Olen pyristellyt onnistuneesti kaikkea laitekuumetta vastaan. Mutta
toki mielessä on speksejä ja ostoslistoja.

Nikonille voisi ostaa jonkun rungon tuolta F70:n ja FT2:n väliltä.
Joku legendaarinen FM2 tai F3 olisi ideaa.

Ja sitten on tuo toinen järjestelmäni eli Leica M. Voi vietävä kun
sille tekisi mieli ostaa runko ja laittaa paukutellen. Mutta
kustannukset ovat mittavat ja valinnanvaikeus on toinen juttu.
* Tarinan runko
** Alkuinnostus

- Vaikka työttömänä rahahanat olivat tiukasti kiinni...
- tuli ostettua hurjasti kaikkea turhaa.
- Alkup. idea oli ostaa yksi halpa runko ja kolme rullaa filmiä
  labrakehityksineen.
- Sen sijaan:
  - kolmet rungot olemassaolevalle systeemille (Nikon F)
  - yksi uusi linssi (toinen kopio suosikistani)
  - kehityssetti
  - kallis skannauskitti
  - erillinen valomittari
  - hurjasti filmiä eri lähteistä
    - ml. fancyjä japanilaisia vintagefilmejä ebaysta
- Innostusta oli paljon, mutta taloudellisena (pihinä) kuvaajana
  kuitenkin valitsin kuvani tarkkaan, ja filmirulla kesti tuskallisen
  pitkään saada valmiiksi.
- Kotikehitys onnistui ja tuotti hyviä onnistumisia. Täydellistä
  jälkeä en saanut, enkä edelleen saa, mutta oman tekemisen fiilis
  korvaa puutteet lopputuloksessa.

** Sekoilu seestyy

- Syksyn edetessä talveksi kuvailu hiljeni odotetusti
- Talvella ei tullut kuvattua paljoa
- Ilford Delta 3200 oli kuitenkin talvikauden kohokohta. Sisälsi
  hyvään aikaan tehdyn sumuisen Helsingin kävelyn kuvia ja käytännössä
  vain onnistuneita kuvia mm. joululta.
- Toinen kohokohta oli loppusyksyn Kentmere 400, puskettu 1600:een ja
  jolla oli loisteliaita kuvia ei pelkästään Tallinnasta vaan myös
  hieman ihmiskuvausta Helsingissä!
- Lähimatkaillessa filmi syrjäytti digin 100%
  - Jos kuva ei ollut filmille, ei ole ottamisen arvoinen
- ... mutta isot ulkomaanreissut tehtiin pelkän digin kanssa.
  - Japanin reissu oli odotettuun tapaan tuottoisa ja niitä kuvia
    'kehiteltiin' 6 kuukautta verkkaiseen tahtiin.(a)

** Kevät

- Sakurarulla eksoottiselle japanilaiselle Washi X -filmille
- mutta filmin kehitys meni mönkään
- Se ei ollut riittävästi lannistamaan touhuja.
- Kuvasin ahkerasti heti toisen rullan Washi X:ää ja sitten
  Santacoloria ja kehitin ne itse ja niistä tuli värifilmien
  parhaimmistoa.
- Kehityskemikaalien laadun ja potenssin tarkkailu on nyt kuitenkin
  asia, jota pitää vähän opiskella jotta voin luottavaisemmin kehittää
  jatkossa.

** Kesä

- Töiden saaminen syystäkin hidasti valokuvaharrastusta, muiden syiden
  ohella
- Värifilmin skannailu ja värien fiksaaminen on saanut harjoitusta.(b)
- Kuvaustahti räjähti loppukesän kotimaanreissulla ihan uusiin
  lukemiin. Täysi rulla Kodak Goldia meni kuudessa tunnissa!
  Seuraavaksi ladattu Ultramax 400-24 ei kestänyt sekään kuin
  vuorokauden.

** Missä ollaan nyt

- Laitehankintoja (filmiin liittyen) ei ole onneksi ollut syksyn
  jälkeen
- (a) => Hyvällä kameralla napattuja diginegatiiveja on suunnaton ilo
  ja vaivattomuus työstää verrattuna filmiin. Tämä on iso erävoitto
  digin puoleen.
- (b) => vastaavasti vaikka värifilmin skannaaminen ja värin
  säätäminen onkin mennyt hyvään suuntaan, on kohtalainen pettymys
  todeta omakohtaisesti värikehittämisen realiteetit: filmin
  ominaisväri on aika vaikea käsite. Digiskannausta on helppo säätää
  haluamaansa makuun ja vaikka tämä on hyvä, eri filmit tasapäistyvät
  ja yksi iso viehätys filmikuvaamisesta on menettänyt potenssiaan.
- Keväinen kehitysfaili ja oma verkkainen valokuvaustahtini nostaa
  kysymyksen: pitäisikö laittaa filmit labrakehitettäväksi jatkossa?
- Laskin että omalla tahdillani se menee noin about tasoihin jos
  kehitytän filmit labrassa vs ostan kolmessa kuukaudessa vanhenevia
  kemikaaleja ja kehitän itse.
- Vaihtoehtoisesti voin keräillä filmiä jääkaapin nurkkaan ja
  kehitellä isommat satsit kahdesti vuoteen, mutta haluanko sillä
  tavalla jemmailla? Rahallinen säästökään ei ole kuin reilu kymppi
  korkeintaan.

** Opittua

- Nopeat filmit enemmän mieleeni. Rae ei haittaa.
- Kolmijalka ilman lankalaukaisinta = turha.
- Keskiformaatti ei enää innosta kamalasti systeemin painon takia.

** Pohdintaa

- Pitäisikö tehdä kuten moni muu filmikuvaaja tekee? Omistaa
  filmikuvaus mustavalkoiselle ja jättää väri suosiolla digille.
- Viimesyksyiset/talviset kohokohdat ovat kaikki kuvattu
  mustavalkofilmille ja sattumoisin myös automaattisella F70:llä.
* Vuosi filmikuvaamista                                        :kamera:filmi:

Syyskuussa 2023 filmikipinä syttyi liekiksi. Mitä vuodessa ehti
tapahtua?

** Luomistarina

Siihen aikaan olin ollut sen puolisen vuotta työttömänä, mutta
rahahanat menojen suhteen olivat vielä suhteellisen auki. Valokuvaus
oli harrastuksenani yleisesti hiljentynyt aika vähiin. Tiesin, että
filmi tai mikään muukaan kameralaite ei elvyttäisi harrastusta...
mutta siitä huolimatta päätin nyt mennä siihen. Järkeä ei konsultoida
näissä asioissa.

Suunnitelma oli tehdä hyvin pieni ja rajoitettu kokeilu: yksi halpa
runko, jolle olisi jo linssit entuudestaan. Kolme rullaa filmiä ja
niille kehitykset. Kokonaisuutena tämä maksaisi satasen pintaan ja
voisin viettää syyskautta sitten rauhassa fiilistellen filmin kanssa.

No, vähemmän yllättäen mopo lähti käsistä lähestulkoon heti portilla.
Yhden edullisen (edullisuus on minulle suhteellinen käsite, tällä
kertaa se tarkoitti 70 euroa) kamerarungon sijaan ostin kolme
edullista runkoa (80, 70, ja 30 euroa). Kolme rullaa filmiä
kehityksineen muuttui syys-lokakuun aikana joksikin 30 rullaksi (!).
Labrakehitykset peruin ja sen sijaan ostin kotikehityskitin
kemikaaleineen ja kalliine skannaustyökaluineen.

Rahaa upposi äkkiä puolisen tonnia tähän pieneen kokeiluun.
Kuherruskuukaudenkaan aikana en kuitenkaan valottanut emulsiota ihan
jatkuvalla syötöllä. Olin säästeliäs ja tarkka valottaja. 36 ruudun
rullat kestivät (ja kestävät ajoittain edelleenkin) tuskallisen
pitkään ennen kuin ne 'saa' kehittää.

Mitä kotikehitykseen tulee, epäonnistumisia ei tullut, vaikka
värikehitys on vielä käsissäni todella 'low fidelity', monenlaisten
värivirheiden kanssa.

Siinä oli onnistumisen makua ja itse tehtynä myös tekemisen makua.
Harrastus oli saanut hetkellisesti uutta pontta alleen, kuten
odotettuakin.

** Sekoilu seestyy

Olipa laitteet mitä tahansa, syksyn muuttuessa talveksi kuvaustahti
hiljeni, kuten tapahtuu joka vuosi.

Kuitenkin tältä kaudelta minulla on käsissäni kaksi erinomaista rullaa
kuvattua filmiä, hyviä onnistumisia. Mustavalkoista Ilford Kentmere
400 -filmiä ja huippurakeista Ilford Delta 3200 -tavaraa. Nopeaa
tavaraa kumpikin. Rae ei haittaa ja ylimääräinen nopeus on aina
tervetullut. Filmin kanssa voit periaatteessa aina ylivalottaa jos et
tarvitse kaikkea vauhtia.

Digikuvaus käytännössä loppui kuin seinään kun filmivillitys alkoi.
Fiilis oli että jos kuva ei ole filmille niin se ei ole ottamisen
arvoinen. Tämä siis näin lähimatkailussa.

Kun kävin Japanissa tammikuussa, oli ilmiselvää alusta alkaen että se
tehdään digillä. Matka oli tietenkin erittäin tuottoisa ja meni kuusi
kuukautta saada kaikki diginegatiivit läpikäytyä. Pidetään tämä
mielessä (a).

** Kevään tuulia

Pitkän talven jälkeen päästiin viimein kevään valoon. Kirsikankukinnan
taltiointi filmille oli odotettu tapahtuma, ja hyvä motivaattori käydä
kirsikkakierroksilla kaupungilla.

Laitoin kameraan premiumiksi kokemaani japanilaista nyrkkipajan Washi
X -värifilmiä. Joitain perustyhmiä valotuksia tuli tehtyä.

Mokasin kehityksen kuitenkin totaalisesti (ensimmäistä kertaa) ja
filmi valmistui typötyhjänä. Syy oli potenssin menettänyt kehitysaine,
joka ei tehnyt filmille mitään. Hiljalleen kuvaavalle näiden
kemikaalien lyhyt hyllyaika on isoin harmi tässä koko hommassa.

En lannistunut tästä epäonnistumisesta, vaan latasin oitis kameraan
toisen rullan Washi X:ää ja sen jälkeen Santacolor 100 -filmiä. Näiden
kehitys meni 100% nappiin ja olivat myös sisällöltäänkin rullina ihan
asiallisia.

** Kesästä tähän hetkeen

Asioita piristi huomattavasti töiden saanti. Kaikkea muuta paitsi
valokuvaamista, siis. Juhannuksen jälkeen aloitetut työt
ymmärrettävästi löivät jarruja kaikelle muulle harrastamiselle.
Valokuvaus, joka on ollut jo muutenkin hiljaista, sai ensimmäisenä
ottaa takapakkia.

Värifilmin skannailu ja värien kuosiinsaaminen, joka on vaikea
taiteenlaji, sai uutta harjoitusta kesällä. Pidetään tämä ajatus! (B)

Hiljaisten kotoilusesonkien välissä tehdyt reissut kotimaassa ovat nyt
ihan viimeaikoina räjähtäneet kuvausmäärien suhteen. Alan tällä
hetkellä ottaa kuvia filmille kuin se olisi ilmaista kuin digi. Täysi
rulla Kodak Goldia meni kuudessa tunnissa! Ennenkuulumatonta minulle.
Seuraavaksi ladattu Ultramax ei sekään kestänyt kuin vuorokauden.

** Vuotta myöhemmin: missä ollaan nyt

Olen pidättäytynyt laitehankinnoista, mikä on tietenkin aina hyvä.
Mutta vietänkö nyt jonkinlaista "paluu todellisuuteen" -kautta filmin
suhteen?

Palataan kohtaan (A) aiempaa: filmikuvien kehittely on sinänsä
yksinkertaista mutta paljoa kuville ei voi aina tehdä ennen kuin ne
hajoavat käsiin. Ulkomaanreissun digikuvat sen sijaan, voi veljet.
Uskomaton joustavuus ja tietenkin korkea fideliteetti myös filmiin
verrattuna. Pimiötyöskentelyn ilo näiden digikuvien kanssa on selkeä
erävoitto digin puoleen, luonnollisesti.

Vastavuoroisesti palataan kesän tuoreeseen kehittymiseeni värifilmin
kehityksen kanssa kohdasta (B): tämä ei nyt ollut ihan uutisia mutta
printtifilmi on erittäin joustava media, jonka voi loppupeleissä
digiskannista käsitellä pitkälti haluamaansa suuntaan. Iso osa
värifilmin taiasta ropisee pois, jos voin ottaa jonkun filmin X ja
toisen filmin Y ja kehittää niistä pitkälti samannäköisiä. Onko tässä
sittenkään mieltä? Ostin premiumfilmejä vuosi sitten sillä ajatuksella
että niiden 'ominaislook' olisi jotain, jota ei digillä voi toistaa.
Nyt se idea on haastettu.

Edellisestä kehityssesiostakin on kulunut taas kuukausia ja alan
pelätä kemikaalien laadun puolesta. Kynnys kehittää kasvaa päivä
päivältä, plus aloittamisen laiskuus. Keväinen epäonnistuminen
kummittelee takaraivossa.

Olisiko kotikehityksen sijaan aika vain dumpata rullat labraan
kehitettäväksi? Yksi murheenkryyni vähemmäksi. Skannaisin ja
värikäsittelisin itse kuitenkin. Omalla verkkaisella kuvaustahdillani
olen laskenut, että labra- ja kotikehitys maksavat kutakuinkin saman,
koska niillä kemikaaleilla on se mainittu parin kuukauden käyttöikä.

(Tottakai voisin kuvailla filmiä ja keräillä sitä jääkaapin nurkkaan
ja kehitellä isot pinot filmiä kerralla vastasotkettuihin
kemikaaleihin niin saisin luotettavaa laatua. Mutta silloin kuvia
pitäisi odotella pitkä tovi, ja rahallinen säästö olisi vain kympin,
kaksi, vuositasolla.)

Olen nyt loppukesästä lähtien alkanut kantaa enemmän digiä mukanani.
Hyvät ja luotettavat kehitykset (per kohta (A)) painavat hieman
vaakakupissa. Ensimmäinen filmivillityksen aalto on ehkä ohi. Onko
koko filmikokeilun aika?

** Vuoden aikana opittua

Nopeat filmit ovat mieleeni. Kentmere 400 valottuu tosi nätisti
1600-herkkyyksisenä. Delta 3200 on päheää tavaraa sekin, vaikka sen
rae onkin jo aikamoista puuroa.

Värifilmissä 400-nopeuksiset ovat tosi bueno. Pidän maltillisesta
rakeesta suhteessa nopeuteen.

Kolmijalka ilman lankalaukaisinta: turhake. Pitää yrittää muistaa aina
pakata kumpikin mukaan, ei kolmijalkaa yksinään.

Keskiformaatti saattoi tuntua hyvältä yhteen aikaan, mutta kaluston
ylenpalttinen paino ei viehätä yhtään. Yksi probleema filmissä
muutenkin on tämä paino.

Pohdintaa: vuoden hienoimmat kokemukset ovat olleet
täysautomaattisella muovilelulla (29 euroa, Nikon F70) otetut
mustavalkokuvat. Otanko vihjeestä vaarin? Hyvä valotusmittaus kameraan
rakennettuna on asia, jonka digikuvaajat ovat ottaneet käytännössä
aina itsestäänselvyytenä.

Haluaisin ehkä samanlaisen täysautomaattisen Nikonin, mutta jos se
olisi hieman pienempi ja vähemmän muovinen kuin tuo F70 niin olisi
kiva. Olen vähän pohtinut, että elpyisikö filmikuvaus vähän, jos
ostaisin jonkun kivan mittaetsinpokkarin (esimerkiksi Canonet 19).
Sykli uusiutuu...
