#+TITLE: Helsinki: Uusi uljas maailma
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Helsinki: Uusi uljas maailma                         :helsinki:asunto:
CLOSED: [2019-06-11 Tue 19:21]
:LOGBOOK:
- State "DONE"       from              [2019-06-11 Tue 19:21]
:END:

Muutto Helsinkiin tapahtui lieviä lihassärkyjä lukuunottamatta kivutta
perjantaina 24.5. päivä ja nyt sitä ollaan oltu töölöläisiä reilut
pari viikkoa. Minkälainen on tämä eteeni aukeava uusi uljas maailma?

** Muuttohommat ja asunto

Muutto tapahtui kyllä mallikkaasti. Perjantaina aamuvarhain saatiin
tavarat autoon ja oltiin pihasta aamukahdeksalta. Helsingissä oltiin
ja kaikki kannettuna iltapäivän klo neljään mennessä! Niin aikaisin ei
kyllä ole muuttoa saanut menemään, etenkin näin pitkän matkan kanssa
vielä. Kävin tutkimassa lähistöni kauppoja ja postilaatikoita --
Caloniuksenkadun Alepa on aika kiva, vaikka pieni onkin.

Muuttoviikonloppu vähän järkytti sillä, miten hiljainen paikka tämä
asunto oikeasti onkaan. Naapureista en kuullut yhtä pihaustakaan
pariin päivään, ja myöhemmin vielä kuulin, että MM-kultaa juhlittiin
pitkin Helsinkiä railakkaasti. Aijaa! Talo on tosi hiljainen ja vain
kantapääastuja kykenee rikkomaan illuusion ihmisettömästä elämästä
tyhjiössä. Onneksi talossa taitaa olla vain yksi sellainen.

Kun astuin perjantaina vähän ulos jalottelemaan ja koeajamaan
lähikauppoja, sisätilojen hiljaisuus kääntyi ovenavauksessa
miellyttäväksi urbaaniksi äänimaisemaksi ratikan raiteiden
kirskumisesta ja tasaisesta liikenteen hurinasta. Tämähän on juuri se
unelma, josta olen haaveillut jo vuosia?! Hipihiljaista sisällä ja
kaupungin vilinää heti oven takana.

Tämä on myös ensimmäinen kerta, kun en ole asunut ylimmässä
kerroksessa. Sateen ropinaa jään kaipaamaan.

ATK:t ja hifit purin käyttövalmiiksi vasta paria päivää myöhemmin,
mikä salli muuttolaatikoiden purkamiseen keskittymisen. Tai ulkona
seikkailun, sekin tietty. Nettiyhteys saatiin pystyyn seuraavana
maanantaina. Vauhdikas yhteys on vauhdikas, vaikka ulkomaan kuitu
vähän kuristaakin.

Ensin täällä oli ahdasta, nyt täällä on avaraa. Huonejärjestelyni on
alustavasti vähän vaillinainen, mutta tässä on aikaa kehitellä uusi ja
parempi. Keittiössä ja eteisessä on tyhjää kaappitilaa,
sängynaluslaatikoita voisi ostaa, kunhan ensin keksii niihin jotain
sullottavaa.

** HKI

Asuinalueena Töölö on osoittautunut mielettömän hyväksi paikaksi.
Erinomaiset yhteydet Kallion ja Kampin suuntaan, palveluita on
äärellään ja itse talo niin hiljainen.

Vaikka Etu-Töölön rakennukset ulkoa päin eivät ole
Kaartinkaupunki/Ullanlinnatasoisia unelmamestoja, löytyy alueen pikku
puistoista kyllä mitä erinomaisimmin idylliä ja kauneutta.

Taka-Töölössäkin on runsaasti hyvää. Töölöntori nyt on karsea
parkkipaikka, mutta näkymät alaspäin aukeavalle Topeliuksenkadulle
ovat varsin urbaani-idylliset; Töölöntullin solmukohta on miellyttävää
pikku vilinää täynnä; pohjoinen Mansku on komeampi ja kiinnostavampi
kuin muistelinkaan; Töölön kisahalli on varsin urbaani kohtaamispaikka.

Mitä enemmän selailen paikkoja, sitä enemmän näen, miten paljon
minulla on vielä nähtävää. Olen toistaiseksi kolunnut paikkoja
pintapuolisesti ja kun päivät kääntyvät viikoiksi ja viikot
kuukausiksi niin olen ehtinyt koluta aika runsaasti myös pintaa
syvemmältä.

Ja parin viikon päästä pitää todeta, miten tuo työmatkaliikkuminen nyt
onnistuu, vai onnistuuko. Otanko ABC-lipun vai mitä teen. Omaa autoa
en ole kaivannut!
