#+TITLE: Hyvinkää
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Hyvinkää                                     :asunto:helsinki:sandels:
CLOSED: [2020-12-03 Thu 18:48]
:LOGBOOK:
- State "DONE"       from              [2020-12-03 Thu 18:48]
:END:

45 päivää sitten olin Iisalmessa vierailemassa ja sain kipinän
omistusasumisesta. Seuraavalla viikolla olen luultavasti
allekirjoittamassa digitaalisia kauppakirjoja hyvinkääläisestä
kaksiosta.

Helsinki vastaan Kuopio vastaan (myöhäinen kilpailija) Hyvinkää, tässä
ne minun vaihtoehdot olivat. Edellisen kerran kirjoitin tänne että
tämä haikailu Kuopion suuntaan on turhan utopistinen työmarkkinoiden
nimissä, ja että koko soppa lähinnä liittyy [[file:./16-kuukautta.org][16 kuukauden rajapyykkiin]].
Nykyisen työni puolesta mikä tahansa paikka kelpaa mutta tulevaisuutta
ajatellen jouduin mietiskelemään vaihtoehtoja myös uusien töiden
kannalta. Hyvinkää nousi esiin vaihtoehtona. Hyvinkää käy järkeen.

** Hyvinkää käy järkeen

Hyvinkää käy järkeen. Siinä on ihan hyvä motto kaupungille. Se ei
varmasti vetoa kenenkään tunteisiin vaan se on korkeintaankin
järkivalinta kun halutaan olla PK-seudun tuntumassa ja säästää rahaa
asumisessa.

Ei toki kovin mairitteleva mainospuhe kaupungille mutta mitä sitä
turhaan koristelemaan totuutta.

Hyvinkää asettuu ydin-Kuopiota halvemmalle tasolle, mutta asuntojen
hinnat eivät sinänsä kosketa minua. Näillä koroilla ja pankkien
marginaaleilla ei totisesti tunnu missään, tarvitseeko asuntolainaa
50, 100 vai 200 tuhatta. Toki rajallisen käsirahan rajoissa Helsingin
hinnat jäävät vielä itseltäni ulottumattomiin.

Helsinki ja Kuopio vetoavat tunteisiin. Töölössä on suoraan sanoen
aika eeppinen olo kun voi kävellä kotiaan rautatieasemalta vartissa.
Tämä olo on tietysti muillakin täällä asujilla, ei näistä asunnoista
muuten tämmöisiä hintoja ja vuokria voitaisi pyytää.

Hyvinkää ei ole urbaania seutua kuten Helsinki. Se on mopoilijoiden
valtakuntaa, lapsiperheitä ja kaikkea maalais-Suomeen liitettävää.
Sivustakuulluissa keskusteluissa viitattiin Tampereeseen melkein yhtä
paljon kuin Helsinkiinkin.

Olen Hyvinkäällä käynyt nyt neljästi eläissäni ja ehkäpä puhutaan n.
kuudesta tunnista "boots on the ground". Kaikki vielä pimeän aikaan.
Voi olla kiinnostava herätä joku päivä uudessa asunnossani ja nähdä,
miltä täällä näyttää valoisan aikaan.

Järkeen ja taloudelliseen vastuuntuntoon Hyvinkää istuu hyvin, mutta
kovin eksoottista elämää en kykene visioimaan siellä.

Hyvinkään kanssa voin vain olla tyytyväinen että siitä on näppärä
tulla Helsinkiin lyhyessä ajassa. 15 minuuttia junalle, 45 minuuttia
junalla ytimeen. Se ei ole lainkaan paha. Tallinnan tai Tukholman
risteilyt, taikka ulkomaanlennotkaan sen puoleen eivät ole
oleellisesti kauempana kuin mitä ne nyt ovat minua Töölöstä.

Hyvinkään läheinen sijainti PK-seudun kupeessa mahdollistaa helpon
PK-alueen palveluiden hyödyntämisen: maan halvimmat vuokra-autot
esimerkkinä. Moni muukin on halpaa Uudellamaalla.

** Töölö: jackpot

Helsinkiin kun suunnittelin silloin talvella 2018-19 niin Ullanlinna,
Punavuori ja Kruununhaka olivat niitä seksiwau paikkoja, joissa näin
urbaania idylliä suunnattomasti. Kuitenkin hyvän sattuman kautta
löysin asunnoista parhaan etu-Töölöstä ja ahkeran asumisen myötä
Töölön alue, niin etu- kuin taka-Töölö ja mikseipä Meilahtikin, on nyt
erittäin positiivisesti jättänyt hyvän jäljen minuun.

Tämä Töölön asunto on vuonna 1925 rakennetussa tiilitalossa ja on
äänieristeiden ja naapurimelun suhteen poikkeuksellisen rauhallinen ja
loistelias paikka. Korkeat huoneet, fiksu huoneasettelu, erinomaiset
liikenneyhteydet ja herrasmiesmäinen Töölö: Museokatu, Arkadiankatu,
kaikki, kaikki niin lähellä. Tämä puhuttelee kaupunki-idyllistä
nauttivaa mitä syvimmällä tavalla. Siihen päälle kun laitetaan vielä
että hintataso on kantakaupungin tasolla maltillinen -- tasoa Kallio
mutta ilman kalliolaisia. Onko tämän parempaa?

On tilastollisesti aika epätodennäköistä että mikään ulkoapäin
arvioiden valittu kerrostaloasunto tulisi olemaan yhtä rauhallinen tai
rauhallisempi kuin tämä Töölön asunto. Se on katkera totuus, joka
minun on nieltävä. Kun asetun taloksi, ehkäpä näillä pessimismiin
kallistuvilla ennakko-odotuksillani voin pärjätä todellisuuden
hakatessa päälle.

** Sandels

Kaksi asuntoa pisti silmään Hyvinkään tarjonnasta, ja tämä on se
toinen niistä. Se valinta. Sandelininkadulla olympiavuoden 1952
tiilitalossa ylimmän kerroksen korkein huonein ja alkuperäisin
lautalattioin tyylikkään retrosti pinnoitettu asunto täten saakoon
lempinimen Sandels oitis.

Sandels on 150 metrin päässä Lidlistä, 600 metrin päässä Hyvinkään
isoista kauppakeskuksista (Willa) ja ylipäänsä hieman alle 15 minuutin
kävelymatkan päässä juna-asemasta. Kilpaileva asunto olisi ollut
marginaalisesti kauempana junasta, toisaalta hieman lähempänä Willaa
mutta lähin ruokakauppa olisi ollut yhtä lailla kauempana. Kilpailijan
paras etu oli 60 eur/kk pienempi hoitovastike, joskin tämä alennus
johtuu neliöiden vähyydestä, ei siitä että hoitovastike olisi neliöltä
mitenkään pieni.

Päädyin hieman törsäämään ja ottamaan isomman asunnon isommilla
hoitovastikkeilla, vaikka jotain 30 olisi ihan riittävä minulle. Uusi
on 50 ja rapiat.

Hyvinkäästä minulla on sellainen intohimoton kuva juuri nyt, mutta se
on hyvä paikka aloittaa suhde uuteen asuinpaikkaan, eikö.

Tästä tulee minulle todellisuutta alkuvuodesta 2021.

** 2021

Hyvinkää ja Sandels vievät oman aikansa kun asetun taloksi, mutta 2021
on varmasti aikamoinen vuoristorata sen asettumisen jälkeen.
Ylimääräinen käteenjäävä raha, pakkosäästäminen, asuinkulut. Voin vain
pelätä, millä eri tavoilla onnistun polttamaan käteenjäävää rahaa
kamerakaupoilla jatkossa.

Mutta ehkäpä paras puoli Hyvinkäässä voi olla ensialkuun kotimaan
matkailun uudelleenvirittely. Sätöksestä käsin tuli käytyä eri
paikoilla. Helsingissä matkailu supistui kokonaan, tietysti järkevistä
syistä: päällisin puolin ensin vuonna 2019 uusi kotikaupunki oli
edessäni ja tutkimusta vaille, sitten vuonna 2020 koronan aiheuttama
sotku löi näpeille kolmeen eri otteeseen, kolme eri ulkomaanreissua.
Siinä sekaannuksen seassa en vallan hoksannut että kotimaan matkailu
olisi ollut mitä järkevin idea.

Käytiin kyllä veljen kanssa vajaan viikon reissu Saanalla Lapissa. Se
ei ollut huono reissu, olisi vain pitänyt toteuttaa enemmän tuota
samaa omasta toimesta.

Hyvinkäällä tulee kutakuinkin varmasti toteutettua oheisia juttuja:
monenmonta vierailua Helsingissä, mukaanlukien hotelliöitä.
Junamatkoja Tampereelle, Turkuun pariksi yöksi. Auton vuokraamista ja
ajelua ympäriinsä. Kenties Tallinnaa myös risteillen, riippuen miten
koronahomma etenee.

2017 ja 2018 tein ahkerasti kotimaanmatkailua ja olen nyt jälkikäteen
valitellut itselleni kun en Helsingissä ollessani ole edes Tampereelle
tai Turkuun mennyt vaikka niin lähellä ovat maantieteellisesti. Tämä
tulee muuttumaan.

Koko valokuvaushomma ja katukuvaus tulee myös menemään vähän uusiksi
tavalla tai toisella Hyvinkään myötä. Urbaani skene ei ole enää rapun
ovesta poistumalla edessäni vaan siinä on se pieni tunnin matkaamisen
kynnys että pääsen Helsinkiin. Se tulee toimimaan kyllä, sitä en
itseasiassa epäile.

Semmoinen on tämä homma. Ehkä koronarajoituksilla on oma lusikkansa
sopassa että näin "luovutin" Helsingin suhteen omasta mielestäni
aikaisin mutta ei tätä peliliikettä kukaan voi varsinaisesti huonona
pitää. 

Kaupat on hierottu. Odotellaan vain että raha pääsee vaihtamaan
omistajaansa, ja sitten avaimet. Näinä päivinä lähinnä jännitetään
että pääseekö Uudeltamaalta viettämään joulua laisinkaan maalle vai
ei.
