* DONE Joensuuhun hinnalla millä hyvänsä                             :asunto:
CLOSED: [2013-03-08 Fri 18:03]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-03-09 Sat 18:03]
:END:

16 kuukauden Outokumpuilun jälkeen sitä pääsee viimein muuttamaan
Joensuuhun. Hinta (asumistaso) tuntuisi äkkiseltään kevyeltä, mutta
on se aika kova kuitenkin.

Uusi asunto on Joensuun ruutukaava-aluetta, kuten kuuluukin olla.
Yliopistolle on 15 minuutin matka kävellen. Ei riippuvuuksia
busseihin, ei aikatauluja. Taivas.

Asunto maksaa välittömine kuluineen (vuokra + kommuutti + vesi)
noin 35 euroa kuussa enemmän kuin Outokummussa. Hieman enemmän kuin
mitä olin valmis ottamaan, mutta kohtuuhintaista asuntoa on
metsästelty hyvät tovit. Vaikka olisi voinut tärpätä paremminkin,
nyt tärppäsi hyvin.

Lisäkustannus on kouluaikoina tuo 35 euroa; kaikille
kesäkuukausille ei Okussa bussia tarvinnut, joten niille
kuukausille lisäkustannus on satasen suurempi. Kaikki sen parempi;
motivoipa enemmän työnhakuun!

Kämppä on tietenkin lokaatioltaan erinomaisella sijainnilla
ylimmässä kerroksessa ja kohtuuhyvin lähellä palveluita
(Outokummussa on joitain palveluita lähempänäkin, mutta vastineeksi
on tuskaisia ylämäkiä ja huoltoaseman metelit.)

Saattaa olla, että vain muutan Okun huoltoasemahälyt hieman
kalliimmaksi naapurihälyksi Joensuussa. Naapurihälyt ovat hieman
korvaantunkeutuvaisempaa, mutta niitä vastaan on myös ehkä helpompi
taistella. Asiaa ei pitäisi pohtia ennen kuin olen saanut sen
kaikukammion täytettyä huonekaluilla. Saattaa yksi jos toinenkin
meteli vaimentua yksinään sillä.

Pysyviä töitä voisin mielelläni ottaa Kotkan kaltaisista
ei-opiskelijakaupungeista, joissa on erinomainen ja tiivis
keskusta. Helsinki ei kiinnosta pätkääkään hajanaisuuden ja kalliin
keskustan takia. Vaikka HSL on parasta, mitä Suomesta saa, ei ole
tarpeeksi hyvä.

** Haasteita

Tämä asunto on haasteinen asunto. Ikkunat länteen, ei verhoja ja
vapaa huoneleiska. Keittiön tuuletushormista kuuluu naapurien
äänet melko vapaasti. Ruuvailla ei kuulema seiniin saa ilman
lupaa.

Haasteita riittää... ja näihin haasteisiin on mukava vastata.
Koulunkäynti siinä ohessa teettää vain vähän työtä rahasta
puhumattakaan. Näissä asioissa voi vaipua epätoivoon tai ymmärtää,
että joskus on ponnistettava vähän matalempaa kuin tavallisesti.
Ja Joensuussa on helppoa ponnistaa, kun on rautakaupat lähellä.
