#+TITLE: Kalorien laskeminen on edennyt hyvin!
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Kalorien laskeminen on edennyt hyvin!                        :kalorit:
CLOSED: [2020-09-08 Tue 19:01]
:LOGBOOK:
- State "DONE"       from              [2020-09-08 Tue 19:01]
:END:

Appsi-ylilordit sanovat, että olen ollut kalorien laskemisessa mukana
nyt 56 päivää eli pian kaksi kuukautta. 1500 kilokalorin
päivätavoitteen olen kyennyt pitämään kaikkina päivinä kun olen
kyennyt seuraamaan tarkasti syömiäni lukuja.

En näe vielä mitään isoja muutoksia ulospäin, mutta vaaka sanoo jotta
yli viisi kiloa on pudoteltu painoa. Se on aika hyvin omiin
vaatimuksiin ja tavoitteisiin nähden.

1500 kilokalorin päiväbudjetin kanssa on vähän innostunut
monipuolistamaan ruokavaliotaan: idea on löytää vähäkalorisia ja
maistuvia ja täyttäviä ruoka-aineksia. Erilaisia leikkeleitä olen nyt
ujuttanut aamupalaleivän päälle esimerkiksi. Proteiinipitoisia
leikkeleitä löytyy iso pino eri valmistajilta, eikä edes tule aina
katsottua hintalappuakaan.

Joskus joku heräteostos aiheuttaa suurta tuskastelua kun ei
hoksannutkaan katsoa rasvan määrää esimerkiksi. Kaurakeksejä ostin
ison paketin vain huomatakseni että kaksi keksiä on jo 100 kcal.
Turhauttavaa niitä sitten järsiä kun ne eivät mitään tuo pöydälle. Nyt
tulee kiinnitettyä huomiota ravintoarvoihin niin kaupassa kuin ennen
kauppakeikkaa mahdollisesti tehtävässä esitutkinnassa ([[https://foodie.fi][foodie.fi]]).

*Sokerin syönti* on ainakin tainnut romahtaa minulla nyt lyhyessä
ajassa. Ei siitä ole pitkä aika kun oli huhtikuu ja silloin tapasin
ostella säännöllisesti karkkirasioita. En nyt joka viikonloppu mutta
puoli kiloa 1-2 kuukauden välein. Sitten ne alkoivat tympiä ja
siirryin herkuttelemaan jogurtti-mansikkahillo-kupillisella. Ja nyt
näinä päivinä omenan tai banaanin syöminen vastaa jo kaikkea mitä
haluan makealta eväältä.

Joskus myös hulluttelen vallan ja ostan jotain sesonkihedelmiä jos
sattuvat olemaan alennuksessa. Joku satunnainen luumurasia ja
tuoreilla luumuilla herkuttelu tuntuu yhtä juhlalliselta kuin miten
Vito Corleone juhlisti arkea tuoreella päärynällä.

Leipäkin on muuttanut merkitystään nyt. Ennen tilkitsin ja täytin
ateriaa leivällä ilman mitään järkevää syytä. Nyt ateriat menevät
ilman. Aamupala on melkeinpä ainut hetki kun syön. Leipähommissakin
olen vähän antautunut ja ostan välillä jotain, joka ei ole halvinta
mahdollista laatua.

Jogurttien ja margariinin kanssa sama homma. Nyt huimaa vähän päätä
kun mietin että aiemmin saattoi mennä 600-grammainen Lätta-paketti
parissa viikossa! Miten ne kalorit oikein sai palamaan silloin?! Nyt
on Ingmariinia ja Lättaa jääkaapissa ja tällä menolla ne ovat siellä
vielä joulukuussakin. Hyvän ja tuoreen leivän päälle voi laittaa
juustosiivun tai jos oikein hullutellaan niin raejuustoa sellaisenaan.

Juustokin. Se on niin hyvää kyllä että muinoin meni iso 1,25-kiloinen
paketti ihan hujahtaen alas. En ostanut sitä kovin usein juuri sen
takia kun tiesin ettei se kestä pitkään kaapissa. Se oli sellainen
satunnainen herkku. Nyt kun kalorit kirjataan ylös niin juustoakin
menee maltilla ja iso 1,25 kiloa kestää pitkään. Muutenkin rasvaiset
ja epäterveelliset ruoat pystyy yllättäen syömään hyvällä omatunnolla
kun ne ravintoarvojen puolesta istuvat budjetissa hyvin.

Ostin ihan kokeillakseni proteiinipatukoitakin online-tukusta. Oma
proteiininsaanti täyttyy kyllä muutenkin ja halvemmilla aineksilla
mutta on noissa patukoissa oma juttunsa, hyvä kun ostin. Aina voi
laukkuun laittaa omenan ja patukan ja sillä saa hyvät kiksit.

Kun kaikkea voi laskea ja budjetoida, se myös kannustaa lähtemään
kävelylle ihan toisella tavalla. Valokuvaus on iso innostus mutta
joskus ei kuvausmojo ole matkassa niin nyt on aina taustalla apuna
kannustamassa tuo kaloribudjetti.

Kaikin puolin tuntuu että nyt laitan enemmän rahaa ja ostan hieman
enemmän tuorejuttuja kuin aiemmin; mutta toisaalta kun jogurtit ja
juustot kestävät pidempään niin kompensoikohan se noita ruokakuluja?

Kaikin puolin on ollut hyvä diili tämä kalorilaskenta. Ehkä isoin
kiusa tällä hetkellä on tuo kun on lahjakortti leipomoon ja ne on
kaikki niin rasvaisia ruokia ettei kärsisi ostaa. Pakko se on kait
joskus pitää cheat-päiviä.
