#+TITLE: Valokuvien workflow'sta
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Valokuvien workflow'sta                 :fujifilm:kamera:organisointi:
CLOSED: [2017-06-17 Sat 12:52]
:LOGBOOK:
- State "DONE"       from ""           [2017-06-17 Sat 12:52]
:END:

Kuvien ottaminen kameralla on yksi ongelma, kuvien organisointi ja
jälkikäsittely on toinen. Käyn läpi, minkälainen workflow minulla on
nykyisin valokuvien käsittelylle ja valikoinnille ja sitten vähän
tuumailen, mitä voisi tehdä paremmin.

** Nykyinen workflow

Tällä tavalla käsittelen valokuvia tällä hetkellä. Tekniikka ei ole
täydellinen, mutta toimii kiitettävästi silloin kun kuvat otetaan
jpeggeinä ja raakakuvia ei tarvitse käsitellä kovin usein.

1. Tuodaan kuvat kamerasta päivämäärän mukaan nimettyyn hakemistoon.
   (oma skripti hoitaa)
2. JPEGit käännetään tagien perusteella ja ne nimetään sopivasti, ja
   raakakuvat erotellaan omaan hakemistoonsa. (skripti hoitaa)
3. Ennen valintaprosessia otan jpegeistä varmuuskopiot (kovat linkit).
4. Käyn kuvat gqview'llä läpi ja poistan surutta kaikki, mitkä eivät
   ole valokuvina onnistuneita. Duplikaatteja vertailen joskus pitkään
   jotta paras valikoituu... joskus on vaikea valita kahdesta yhtä
   suosikkia. 
5. Merkkaan ylös, mitkä kuvat kaipaisivat vähän käsittelyä,
   käytännössä käsittelyn tarve on kroppaaminen ja valotuksen korjaus.
   Fujifilmin kuville ei tarvitse yleisesti ottaen tehdä
   valkotasapainon korjaamista tai vastaavaa.

   Tämä muistilista näyttää suunnilleen oheiselta:

   #+BEGIN_EXAMPLE
     crop:
     3216 
     3220 
     ...
     3482 
     
     vaihda kuvat päittäin: 3246 <-> 3249
     
     valotus:
     3262
     3270
     3308
   #+END_EXAMPLE
   
6. Kroppaan jpegit jollain häviöttömällä työkalulla. Sopiva työkalu
   on tosin hakusessa.
7. Muut jälkikäsittelyt, kuten valotus ja muut jutut sitten
   Darktablella. Käyn yhden käsittelyä kaipaavan kuvan kerrallaan
   DT:ssä läpi ja vien ne jpegeiksi.

** Puutteita workflow'ssa
 
Tekniikka on kymmeniä vuosia vanha, ja sinänsä toimii, sinänsä olen
tyytymätön joihinkin seikkoihin. Vahingossa poistetun kuvan
palauttaminen onnistuu varmuuskopiosta, jos olen muistanut ottaa
kopiot, ja sittenkin minun pitää vähän kaivella että mikä sen
poistetun kuvan tiedostonimi olikaan.

Häviötön kroppailu on uutta, jota olen alkanut harrastaa. Aiemmin jos
kroppasin, niin kroppasin raakakuvissa. Suoraan Fujin laadukkaista
jpegeistä kroppaaminen on tietty mielekästä kun muuta korjattavaa
kuvassa ei ole. Harmikseni en ole löytänyt hyvin toimivaa työkalua,
joka kroppaisi kuvia siististi. Joko EXIF-tiedot kadotetaan tai
frontend on ihan muilta osin surkea. Lisäksi olisi luontevaa kropata
kuvat suoraan valintaprosessin aikana.

Systeemissä ei ole mitään toimivaa tapaa tagailla kuvia. Isoissa
kuvaseteissä toteutin minimaalisen tagailuskriptin, joka lisää tagit
tiedostonimeen.

Vaikka oikeata jälkikäsittelyä vaativia kuvia syntyykin aika vähän
(esimerkiksi nyt viimeisin lomakeikka Helsingissä tuotti noin 250
kuvaa ja niistä kolme minä tuomitsin uudelleenmuotoiltavaksi
raakakuvista) niin useampikin kuva kyllä nauttisi pienistä
korjailuista.

/Kynnys/ ottaa raakakuva esiin Fuji-JPEG:n sijaan on aika korkea,
koska Fuji tekee niin hyvälaatuiset filmiemulaatiot, korostusten ja
varjojen pelastukset, ja kohinanpoistot, että niitä on /vaikea/ saada
toistettua Darktablessa yhtä esteettisesti. 

Kohina on yksi valitettava probleema. Isoilla herkkyyksillä kuvissa on
kromaattista kohinaa, joka on puhdistettu kameran jpegeissä kauniisti,
mutta Darktablella ei ole löytynyt optimaalisia työkaluja tähän.
Johtuen joistakin tekijöistä saan myös rumia värivirheitä pistemäisiin
valonlähteisiin ja heijastuksiin Darktablella, mutta tätä esiintyy
fuji-raakakuvien lisäksi muilla raakakuvilla. Myös menetän mahdollisen
filmiemulaation ja palaudun oletusväreihin.

** Lightroom

Ymmärtääkseni Lightroom mukailee Fujifilmin kameran tekemiä
prosessointeja monella tasolla (väriemulaatiot ovat saatavilla,
käsittääkseni kohinanvaimennusprofiili on myös). 

*Ironisesti Fujifilm saattaa olla enemmän riippuvainen Lightroomista
kuin vaikkapa Leica Q.* Olettaen, että kummallekin kameralle saisi
hyvät kohinaprofiilit Darktablessa, niin silti vain LR tukisi Fujin
komeita värejä laatikkosuorasti. Q:n kanssa Darktable voi hyvinkin
olla riittävä työkalu ja Lightroom + VSCO vain mukava optio.
Harmittavan vähän tosin löytää netistä vertaistukea kummallekaan
kameralle Darktable-asetuksien etsimisessä. 

Molemmille työkaluille saa filmiemulaatioita, mutta Lightroomille on
valtava valikoima kolmansien osapuolten maksullisia ja laadukkaita
plugineita. Neat Image, VSCO ja Perfectly Clear esimerkkeinä.
Darktablelle saa myös hyvännäköisiä valmistyylejä, mutta ne eivät
oletettavasti voi pärjätä jokaisessa aspektissa.

Kaikin puolin Darktable on avoimeksi työkaluksi erittäin hyvä,
joiltain osin Lightroomia parempi työkalu. Ja joiltain osin huonompi.
Suunnittelufilosofia on hieman erilainen kummassakin, joten
1:1-suhdetta ei koskaan tulla saavuttamaan.

Lyhyesti kuitenkin jos alustariippuvuudet unohdetaan tarkastelusta,
juuri tällä hetkellä Lightroom sallii nopeammat workflow't
kohinanpoiston ja värikäsittelyn päälle, mutta Darktable ei tule
kaukana jäljessä: riittäisi vain käyttää sitä jonkin aikaa kuvien
kehittämiseen ja antaa toimivien valmispresettien kertyä.

** Rauta

Lottovoittokone pelkkään kuvien käsittelyyn olisi ehkä tällä hetkellä
uusi täysillä spekseillä varustettu Surface Pro (12 tuuman tabletti,
hyvät värit, täysi Windows-yhteensopivuus) tai peräti Surface Studio
(isolla kosketusnäytöllä varustettu all-in-one). Siinä ajaisin sitten
Lightroomia kaikilla hienoilla plugineilla.

Lottovoittoa odotellessa olen alkanut lämmetä kokeilemaan
virtualisointiratkaisuja uudelleen. Ja vaikka Intel i5 2500k on
kohtuuvanhana prosessorina huippuhyvä, käytännössä täydellinen
koodailuun ja kevyeen pelailuun, kuvankäsittelyssä on valitettavia
viipeitä. Ja opin vasta hiljan, että uusissa Inteleissä
kerroinlukottomat k-mallit sisältävät VT-d-tukea, joten tämä on omiaan
ruokkimaan kokeiluhaluja.

Jos hommat toimivat oikein, sellaisella raudalla voisin ajaa linuxia
edelleenkin isäntänä ja rautakiihdytettyä Windowsia orjana käytännössä
natiivinopeuksilla. Lightroomin lisäksi voisin lopettaa wine-pelleilyt.
