#+TITLE: Kirjanpidosta: Ledger
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Ledger ja kirjanpito                        :cli:ohjelmistot:editorit:
CLOSED: [2014-02-05 Wed 12:56]
:LOGBOOK:
- State "DONE"       from ""           [2014-02-05 Wed 12:56]
:END:

[[http://www.ledger-cli.org/][Ledger]] on John Wiegleyn visioima ja toteuttama kahdenkertainen
talouskirjanpitosovellus komentoriviympäristöihin. Koska Ledger toimii
kääntäjämallisesti pelkän puhtaan tekstin kanssa, voi sitä täydennellä
ja käsitellä millä tahansa editorilla haluaa. Ja sai viimein minutkin
pitämään kirjaa. Tässä jutussa kerron hieman Ledgeristä ja omasta
kirjanpidostani, jos vaikka joku innostuu mukaan.

Huomio ja disklaimeri: opiskelin taloustaitoa ja kirjanpitoa viimeksi
yläkoulussa. Vaikka osasin tehdä koulukioskiprojektimme
kahdenkertaisen kirjanpidon suurinpiirtein oikein, niin kirjanpidossa
vakiintuneita käytäntöjä en muista juuri lainkaan, enkä myöskään
erityisesti kirjanpitosanaston suomennoksiakaan. Eli joskus puhun
asioista joillain termeillä, jotka tuskin esiintyvät sellaisenaan alan
oppikirjoissa. Ehkä minunkin pitäisi joskus käydä kirjastossa.

** Kirjanpidon peruskäsitteitä

Kahdenkertainen kirjanpito hämää ihmisiä, eikä ihan syyttä. En väitä
osaavani kaikkia sopukoita superhyvin, joten tässä tulee pedagogisesti
puutteellinen esitelmä asiasta.

Kahdenkertaisessa kirjanpidossa (siis siinä kirjanpidossa, josta
puhumme tässä nyt) jokaisella tapahtumalla on "vastatapahtuma" siten,
että kaikki summat menevät aina lopuksi nollaan. Jos ostan kympillä
perunoita, niin lompakostani *hävisi* kymppi, mutta perunakuluihin
tuli kymppi *lisää*.

Kahdenkertaisessa kirjanpidossa on kaikki kiinni niinsanotuissa
tileissä. Nämä tilit eivät ole sama asia kuin pankkitilisi, vaan
kirjanpidollisia tilejä voi tehdä lennosta sitä mukaan kun syntyy
tarvetta. Kirjanpitotilit ovat vain nimettyjä "lokeroita", joihin
erilaiset tulot ja menot on luonteva järjestellä. Ja mikä on luontevaa
kullekin, sen saa aivan itse päättää. Tilejä on viittä erilaista
tyyppiä ja kunkin tyypin alle saa nimetä uusia alatilejä. Viisi
perustiliä ovat:

- Equity (Pääoma) :: Lähtötilanne, eli oikeiden tilien ja velkojen
     määrät siinä vaiheessa kun kirjanpito aloitetaan. Ei tarvita
     muuhun kuin alkunumeroihin.
- Income (Tulot) :: Kaikki raha, joka tulee systeemiin, *otetaan pois*
                    tulotileiltä.
- Expenses (Menot) :: Kaikki raha, joka lähtee systeemistä, *lisätään*
     menotileille.
- Liabilities (Velat) :: Jos raha tulee siten, että se pitää joskus
     kuitata (esimerkiksi luottokortit ja lainat), se tulee pois
     velkatileiltä.
- Assets (Omaisuus) :: Ostat jotain omistaaksesi, omaisuustili on
     oikea paikka. Myös käteisvarat (kuten oikein pankkitilien saldot)
     ja osakkeet ja sen sellainen on hyvä pitää täällä.

Onko riittävän epäselvää nyt? Tehdään konkreettinen [[Esimerkki][esimerkki]] kun
ensiksi tutustutaan Ledgerin käyttämään merkintätapaan.

** Ledgerin tilikirjojen merkkaus

Ledger on siis arkkitehtuuriltaan [[http://www.catb.org/esr/writings/taoup/html/ch11s06.html#id2958199][kääntäjä]], vaikka mitään
binäärimössöä se ei tuotakaan ulos. Tai filtteri, jos halutaan tulkita
ESR:n määritelmiä edelläolevasta toisin. Ledger lukee tilikirjan
annetusta tiedostosta muistiin ja parsii siitä kaikenlaista pientä
informaatiota. Sitten käyttäjä tekee kyselyitä tästä informaatiosta,
kuten vaikka tilinsä saldon. Ledgeriä voi käyttää eräajossa suoraan
komentoriviltä, tai sen voi käynnistää omassa tulkissaan, jolloin
samalla syötteiden parsimisella voi tehdä monet kyselyt.

Ja tämä tilikirjaformaatti, jota Ledger lukee, on tosiaan hyvin
yksinkertainen tekstimuotoinen formaatti, kuten odottaa saattaisi.
Ohessa on mukailtu esimerkki ohjelman [[http://www.ledger-cli.org/][sivuilta]]. Tässä on siis pätkä
tekstitiedostosta, joita kutsun tilikirjoiksi nyt tässä artikkelissa:

#+BEGIN_EXAMPLE
2006-10-15 Exxon
    Expenses:Auto:Gas         $10.00
    Liabilities:MasterCard   $-10.00
#+END_EXAMPLE

On siis ostettu bensaa 15.10.2006 ja tälle tapahtumalle on annettu
/kuvaus/ (ledgerin jargonissa /note/ tai /description/) "Exxon".
Sitten sisennettynä on lista eri /tileistä/ ja muutoksista niille
tileille. Tilille =Expenses:Auto:Gas= on tullut kympin verran lisää
rahaa ja vastaavasti =Liabilities:MasterCard= -nimiseltä tililtä on
hävinnyt samaisen kympin verran. Tilien nimet ovat täysin
vapaavalintaisia ja niissä koulutusta saaneet käyttävät tietynnimisiä
etunimiä ihan perinnesyistä. Niistä oli edellisessä kohdassa.

Nyt tämän esimerkkitiedoston luettuaan Ledger osaa sanoa, että bensaan
on mennyt kymppi ja että MasterCardin luottoa on vingutettu kympillä.
Parempi maksaa jossain vaiheessa pois. Ledger osaa myös tarvittaessa
laskea yhteen puuttuvat numerot, jos yhdestä tapahtuman tileistä
puuttuu rahamäärä. 

** Kattavahko esimerkki
<<Esimerkki>>

Tehdään nyt toivottavasti selkeyttävä esimerkki tähän kaikkeen. Olkoon
meillä avattuna Nordeassa yksi käyttötili ja yksi säästötili. Ja
tileillä on vaikka 1204,45 euroa ja 930 euroa vastaavasti. Ja Nordeaan
avatulla Visa Credit -kortilla on pari kymppiä ostoksia. Ja tällä
skenaariolla aloitamme kahdenkertaisen kirjanpidon ledgerissä.

Tilinavaus tapahtuu pääomatiliä käyttämällä ja lähinnä siitä syystä,
että kahdenkertaisuuden tasapaino säilyy.

#+BEGIN_EXAMPLE
2014-01-01 Kirjanpidon aloittaminen
        Assets:Tilit:Nordea             1204,45 €
        Assets:Tilit:Säästötili         930 €
        Liabilities:Visa                -32,40 €
        Equity:Tilit
#+END_EXAMPLE

Nyt tämä meidän kuvitteellinen tili =Equity:Tilit= on pahasti
pakkasella, mutta se saakin olla. Sen kuuluukin olla. Nyt meillä on
kirjat kunnossa. =Liabilities:Visa= on pakkasella kanssa, ja senkin
kuuluu olla näin. Kuten fysiikassa meillä on jokaiselle voimalle
vastavoima, niin taloustieteessä kullekin tilitapahtumalle on
vastatapahtuma.

Jotta asia valottuu paremmin, päätämmekin vaikka lyhentää tämän
visalaskun oitis nollille. Kun on nettipankissa tehty asianmukainen
siirto, niin kirjataan heti ylös, ettei unohdu:

#+BEGIN_EXAMPLE
2014-01-01 Visan lyhennys
        Assets:Tilit:Nordea             -32,40 €
        Liabilities:Visa                32,40 €
#+END_EXAMPLE

Eli kuten oikeassakin maailmassa tapahtuu, velan lyhentämiseen menee
perhana oikeata käteistä rahaa. Nyt ledger tietää sanoa, että tili
=Liabilities:Visa= on nollilla, mikä on hyvä asia. Ledger
todennäköisesti jättää tämmöisen nollatun tilin ylipäänsä näyttämättä.

Jos käydään kaupassa ja maksetaan Visan Debit-puolella (vähennetään
suoraan korttiin kytketyltä tililtä), niin tapahtuma näyttäisi vaikka
tältä:

#+BEGIN_EXAMPLE
2014-01-05 Ruokaa
        Assets:Tilit:Nordea             -59,30 €
        Expenses:Ruokamenot
#+END_EXAMPLE

Meillä ei ollut tyhjässä tilissä mitään "ruokamenot"-tiliä, mutta
ledger luo kaikenlaiset tilit aina tyhjästä, jos samannimistä ei ole
aiemmin tiedostossa lukenut. Meillä on kaikki valta nimetä asioita
kuten haluamme. Eikä ole pakko kirjoitella puolienglanniksi, minä vain
tapaan tehdä asiat noin. Kaksoispisteet ovat tavallaan kyllä
pakollisia, mutta vain jos haluat että ledger laskeskelee alatilien
saldoja yhteen puolestasi. Asialla ei ole muuta kuin informatiivista
merkitystä. Näkisit esimerkiksi suoraan kaikkien eri tiliesi
kokonaisrahamäärän.

Huomataan myös, että nyt jätin kirjoittamatta vastatapahtuman numerot
ylös. Ledger on sen verran taitava poika, että se laittaa oikean luvun
tuohon puuttuvaan kohtaan. Yhdessä transaktiossa voi olla muutoksia
useampaankin kuin kahteen tiliin, mutta vain yhdestä tilistä saa
jättää numerot pois. Ledger ei osaa tällöin päätellä, mistä ja miten
paljon pitäisi siirtää. Se myös kielii siitä, että Ledgerillä ei voi
tehdä yhdenkertaista kirjanpitoa, vaikka haluaisi. Vain yksinkertaiset
käyttävät yhdenkertaista kirjanpitoa, ja siihen välttää Excelin
tapaiset kikkareet!

Tämä ruokaostos on myös kirjattu menoihin sen takia, että sitä rahaa
ei tulla näkemään uudestaan noin vain. Raha on lähtenyt systeemistä.
Kulutustavarat, kuten ruoka ja polttoaine ja netflix-kuukausimaksut
laitetaan menoihin. Sen sijaan jos ostat kultaa tai bitcoineja tai
jotain arvonsa säilyttävää, kuten asunnon tai auton, ne yleensä
merkitään omaisuudeksi.

Tässä vastineeksi yleinen tapaus, jossa rahaa tulee systeemiin:

#+BEGIN_EXAMPLE
2014-01-16 Palkka
        Assets:Tilit:Nordea             1890,90 €
        Income:Palkka
#+END_EXAMPLE

Raha tulee kirjanpitoon ikään kuin tyhjästä, joten merkitsemme rahan
lähtevän tuloista. Tulotilit ovat /aina miinuksella/, menotilit /aina
plussalla/. Velat aina miinuksella. Omaisuustilit toivottavasti aina
plussalla ja pääomatilit alkutilanteen omaisuuden mukaan joko
miinuksella (hyvä tapaus) tai plussalla.

** Ledgerin peruskäyttö

Hyödynnetään edellisessä luvussa kehiteltyjä tapahtumia ja tutkitaan,
mitä itse ohjelmalla voi nyt tehdä. Jahka Ledger on asennettu tavalla
tai toisella, niin sitä voi lähteä kokeilemaan ylläolevien tapahtumien
avulla. Summa summarum, olkoon tässä koosteena tiedosto =~/tilit=:

#+BEGIN_EXAMPLE
  2014-01-01 Kirjanpidon aloittaminen
          Assets:Tilit:Nordea             1204,45 €
          Assets:Tilit:Säästötili         930 €
          Liabilities:Visa                -32,40 €
          Equity:Tilit
  2014-01-05 Ruokaa
          Assets:Tilit:Nordea             -59,30 €
          Expenses:Ruokamenot
  2014-01-01 Visan lyhennys
          Assets:Tilit:Nordea             -32,40 €
          Liabilities:Visa                32,40 €
  2014-01-16 Palkka
          Assets:Tilit:Nordea             1890,90 €
          Income:Palkka
#+END_EXAMPLE

Sekoitin hieman tapahtumien järjestystä, sillä Ledger ei välitä muusta
kuin päivämääristä.

*** Saldot

Katsoaksemme saldot voimme komentaa Ledgerille =balance= tai lyhyesti
=bal=:

#+BEGIN_SRC sh :results output
ledger -f ~/tilit balance
#+END_SRC

:            3933,65 €  Assets:Tilit
:            3003,65 €    Nordea
:             930,00 €    Säästötili
:           -2102,05 €  Equity:Tilit
:              59,30 €  Expenses:Ruokamenot
:           -1890,90 €  Income:Palkka
: --------------------
:                    0

Ledgerin mielestä tilit on siis tasapainotettu oikein, koska viivan
alle jää nolla, summa on siis nolla. Tässä nähdään myös paremmin, mikä
on näiden tilien ja alitilien merkitys. =Assets= on tili kyllä, mutta
siihen summataan kaikkien samalla alulla nimetyt muut tilit omaksi
tiedoksemme. Sama käy tilille =Assets:Tilit=. Tästä on helppo lukea,
että erilaisilla pankkitileillämme on 3933 euroa ja että ruokaan on
mennyt kaikkinensa melkein 60 euroa.

Kun kirjanpitoa on tehnyt vähän aikaa, voi erilaisia tilejä olla
helposti satakunta erilaista, ja koko saldolistaus voi olla aika
pitkä. Komennolla =bal= voi antaa tarkentavan lisämääreen
tarkasteltavista tileistä:

#+BEGIN_SRC sh :results output
ledger -f ~/tilit bal Assets:Tilit
#+END_SRC

:            3933,65 €  Assets:Tilit
:            3003,65 €    Nordea
:             930,00 €    Säästötili
: --------------------
:            3933,65 €

Kun laitat laskuja maksuun, niiden eräpäivän voi pitää siellä
tulevaisuudessa ihan piruuttaan. Kirjanpidossa tapahtuman päivämäärä
laitetaan tulevaisuuteen, siihen eräpäivään. Valitettavasti se näkyy
Ledgerissä saldoissa kuitenkin jo oitis. Käyttämällä optiota
=--current= tai lyhyemmin =-c= voidaan Ledger kuitenkin laittaa
laskemaan vain /jo tapahtuneita/ tapahtumia (tämä päivä mukaanlukien).
Tilinsä tilannetta voi täten vähän ennakoida vertaamalla saldoja
c-option kanssa (pitäisi olla sama lukema kuin mitä nettipankki
ilmoittaa) ja ilman (mitä oikean saldon pitäisi olla, jahka
viimeinenkin lasku on mennyt veloitukseen).

*** Tapahtumat

Saldot ovat toki usein käytetty toiminto, mutta toinen tärkeä Ledgerin
komento on =register= tai lyhennettynä =reg=.

#+BEGIN_SRC sh :results output
ledger -f ~/tilit reg
#+END_SRC

#+begin_example
14-Jan-01 Kirjanpidon aloitta.. Assets:Tilit:Nordea       1204,45 €    1204,45 €
                                Asset:Tilit:Säästötili     930,00 €    2134,45 €
                                Liabilities:Visa           -32,40 €    2102,05 €
                                Equity:Tilit             -2102,05 €            0
14-Jan-05 Ruokaa                Assets:Tilit:Nordea        -59,30 €     -59,30 €
                                Expenses:Ruokamenot         59,30 €            0
14-Jan-01 Visan lyhennys        Assets:Tilit:Nordea        -32,40 €     -32,40 €
                                Liabilities:Visa            32,40 €            0
14-Jan-16 Palkka                Assets:Tilit:Nordea       1890,90 €    1890,90 €
                                Income:Palkka            -1890,90 €            0
#+end_example

Tämä ei nyt kamalasti hyödytä näin pienen tilikirjan kanssa, mutta
edut alkavat tulla esille, kun tapahtumia on satoja ja pitäisi tutkia
vain viimeisimmän kuukauden juttuja. Tai jos vaikka haluaa katsoa
päivämäärän mukaan lajiteltuna näitä:

#+BEGIN_SRC sh
ledger -f ~/tilit reg --sort date
#+END_SRC

Tapahtumia voi myös suodattaa sopivasti, jos olet etsimässä vain
tiettyjä tapahtumia. Esimerkiksi tapahtuman kuvauksella tai
tapahtumaan liittyvillä tileillä voi rajata vaikka tutkiaksesi vain
ruokaostoksia. Näistä löytyy enemmän ledgerin [[http://www.ledger-cli.org/3.0/doc/ledger3.html][manuaalista]].

Yhden tärkeän voisin ottaa tähän, eli päivämäärien mukaan tehtäviä
rajoitelmia. Optiot =--begin= ja =--end= rajoittavat tapahtumat
annettujen päivämäärien väliin päätepisteet mukaanluettuna. Tässä on
esimerkkinä tapahtumakysely vuoden ensimmäiseltä viikolta. Palkka ei
ole ehtinyt tulla:

#+BEGIN_SRC sh :results output 
ledger -f ~/tilit --begin 2014-01-01 --end 2014-01-07 reg
#+END_SRC

#+RESULTS:
: 14-Jan-01 Kirjanpidon aloitta.. Assets:Tilit:Nordea       1204,45 €    1204,45 €
:                                 Asset:Tilit:Säästötili     930,00 €    2134,45 €
:                                 Liabilities:Visa           -32,40 €    2102,05 €
:                                 Equity:Tilit             -2102,05 €            0
: 14-Jan-05 Ruokaa                Assets:Tilit:Nordea        -59,30 €     -59,30 €
:                                 Expenses:Ruokamenot         59,30 €            0
: 14-Jan-01 Visan lyhennys        Assets:Tilit:Nordea        -32,40 €     -32,40 €
:                                 Liabilities:Visa            32,40 €            0

Muutama erikoistermikin löytyy, jolla säästyy vähän naputtelua.
Nykyisen kalenterikuukauden aikana (eli ensimmäisestä päivästä alkaen)
tehdyt tapahtumat:

#+BEGIN_SRC sh
ledger -f ~/tilit --begin 'this month' reg
#+END_SRC

Ja viimeisimmän kuukauden eli 30 päivän tapahtumat:

#+BEGIN_SRC sh
ledger -f ~/tilit --begin 'last month' reg
#+END_SRC

Mainitut asetukset käyvät kaikki niin saldoihin kuin
tapahtumakyselyihin. Erityisesti edellä mainitut =--current= ja
=--begin= ja =--end= -optiot toimivat hyvin.

*** Ledger on täynnä toimintoja

[[http://www.ledger-cli.org/3.0/doc/ledger3.html][Ledgerin dokumentaatio]] on iso ja kattava pakkaus kaikenlaista, ja
onneksi kaikkea ei tarvitse osata heti. Nämä ovat asioita, joilla
pääsee alkuun ja ainoa vaikeus Ledgerin käytössä on etsiä oikeat
komentoriviliput saadakseen haluamaansa tietoa ulos haluamassaan
muodossa. Esimerkiksi riittävästi kikkailemalla =-W=- tai
=-M=-optioiden kanssa tapahtumakyselyistä saa ulos sopivaa dataa,
josta voi tehdä vaikka Excelillä kuukausikäppyröitä.

Ledger on täysin valuutta-agnostinen. Se ei välitä, lukeeko
rahasummien lopussa tai alussa $, €, USD, BTC tai vaikka *orava*.
Yksiköiden on täsmättävä kyllä keskenään, jotta tileiltä tehtävät
vähennykset ja lisäykset menevät oikein. Mutta samalla tilillä voi
olla vaikka euroja ja dollareita, Ledger ei sitä estä. Ja mikä tahansa
kvantifioitavissa oleva asia voi olla kirjoilla Ledgerissä. Oikein
tarkan markan mies pitää vaikka jääkaappinsa sisältöä kirjanpidossa.
Seuraava rivi on täysin laillinen Ledger-merkintä:

#+BEGIN_EXAMPLE
2014-02-05 Välipala
        Jääkaappi                       -1 omena
        Jääkaappi:Maito                 -2 dl
        Syönnit
#+END_EXAMPLE

Jos samassa tapahtumassa yhdeltä tililtä vähennetään yhtä valuuttaa ja
toiselle tulee toista, Ledger ymmärtää välissä tapahtuneen
valuutanvaihdon ja että käyttäjä on antanut oikeat numerot tiedostoon.
Samalla systeemillä onnistuisi vaikka tuntikirjanpitokin!

Ledger osaa myös tehdä kuukausittaisia automaattitapahtumia ja
budjetointia, mutta niihin en ole lainkaan paneutunut. Ledger tuntee
myös erilaisia maksajaliitteitä ja muuta metatietoa, jos haluaa olla
oikein tarkka asioiden kanssa. Monet näistä hienouksista voi myös
tehdä pelkillä alitileillä.

** Omia käytäntöjäni ja niksejä

Nyt kun kahdenkertainen kirjanpito ja Ledger on jotenkuten selvillä,
on aika hävittää hieman epäselvyyksiä kertoilemalla omia käytäntöjäni
parin vuoden säännöllisen kirjanpidon jälkeen.

*** Lompakon käteinen

Kirjanpitohan on vaivalloista! Aina kun heitän 50-senttisen
keräyslippaaseen tai ostan pullakahvit yliopistolla, joudun tekemään
monta riviä tekstiä tiedostoon.

No ei ihan. Kannattaa vetää itselleen joku raja johonkin, jonka ali
kirjanpitoa ei tehdä. Fyysinen käteinen on yksi hyvä nyrkkisääntö: se
fyysinen käteinen, mitä sinulla on lompakossa tai sukanvarressa on
sellaista, että ei tarvitse pitää kirjaa. Toisin sanoen minä *pidän
kirjaa vain niistä rahoista, jotka joskus näkyvät nettipankissani*.

Jos nostan käteistä automaatilta, niin kirjaan sen tilille
=Expenses:Siirrot= eli tavallaan siirrän tililtä käteen. Vastaavasti
jos käyn pankissa tekemässä talletuksen, niin se tulee tililtä
=Income:Siirrot=.

Tällä systeemillä on myös se sivuvaikutus, että lompakossa lojuvat
pikkurahat käytän huolettomammin, tietäen että niistä ei synny
henkistä krapulaa viimeistään siinä vaiheessa kun naputtelen tilit
tasalle. Ehkä jonkinlainen "roskatili" myös huolettomille
korttiostoksille voi sopia jonkun tyyliin.

*** Ison kauppakuitin pilkkominen

Ruokakaupassakin käydessä harvemmin ostetaan pelkkää ruokaa. Joskus on
joku pesuaine tai deodorantti loppunut, joten sekin menee samalla
matkalla. Ja kotona kädessäsi on yksi kuitti, jossa on yksi
loppusumma. Tämän voi jakaa yhden tapahtuman sisällä erilaisiin
tilisiirtoihin:

#+BEGIN_EXAMPLE
2014-02-05 Ruokaa ja muuta
        Assets:Tilit:OP                 -15 €
        Expenses:Ruoka                  12 €
        Expenses:Koti                   3 €
#+END_EXAMPLE

Ja näin on tili taas tasattuna, eikä ruokaostokset hämärry liiaksi
muista ostoksista. Jos tämmöinen nirhaaminen ei kiinnosta, niin tilin
nimeksi voi harkita jotain yleisempää, vaikka "Elintarvike".

*** Tilien avulla voi tehdä mikrotilastointia

Riippuen vapaa-ajan määrästä ja viettämisestä voi olla "kiinnostavaa"
vaikka erotella kahvi- tai alkoholiostokset erilleen kaikesta ruoasta.
Näin näkee sitten vuosien saatossa, missä suhteessa tulee mitäkin
ostettua, ja kuinka usein! Alitilejä voi rakennella niin listauksista
saa aina ulos myös kokonaiset summat. Minulla on esimerkiksi tämmöisiä
tilejä omassa kirjanpidossani:

#+BEGIN_EXAMPLE
Expenses:Ruoka
Expenses:Ruoka:Kahvi
Expenses:Ruoka:Makeiset
Expenses:Ruokailut
#+END_EXAMPLE

Huomaa ero ruokaostosten ja ruokailujen maksamisten välillä.
=Ruoka=-tilille merkitsen elintarvikeostokset ja =Ruokailut=-tili on
sitten sitä kun syödään tai juodaan "ulkona".

*** Omaisuutta vai menoja?

Kun ostat ruokaa, niin se on aika selvästi menoja. Tai jos tilaat
kahvilassa kahvin. Niitä rahoja ei saa enää takaisin. Helppoja
päätöksiä. Vastaavasti jos ostaa osakkeita tai kultaa, niin ne on
helppo merkitä omaisuudeksi. Joskus ne voi taas realisoida euroiksi
--- toivottavasti voitolla.

Mutta miten pitäisi toimia, kun ostat CD-levyjä? Uuden näppäimistön
tietokoneeseesi? Nopeasti arvonsa menettävän keskitason älypuhelimen?
Auton? Ovatko nämä menoja vai omaisuutta?

Tähän varmasti kaikkein alkeellisin taloustieteen ykköskurssin
oppikirja ottaa hyvin kantaa, mutta minä lähdin siitä liikkeelle, että
kaikki, joka on jollain tavalla jälleenmyytävissä, on omaisuutta.
/Paitsi että/ avaamattomat ruokajutut voivat vaikka mennä kaverille
pikkurahalla ja että älypuhelimesta ei saa parin vuoden päästä kuin
murto-osan hinnasta takaisin. Eli tämä on vahvasti sellaista oman maun
mukaan tehtävää rajanvetoa. Ehkä viisainta olisi pitää omaisuustilit
mahdollisimman tyhjinä, pitää vain pankkitilit ja mahdolliset osakkeet
siellä.

Jos sattuu myymään jotain, joka ei ole omaisuudessa, niin sen voi
merkitä itselleen tuloksi. Jos myy jotain omaisuudesta pois, niin se
pitää tietysti vähentää omaisuudesta. Tässäkin tulee pieni dilemma
eteen:

#+BEGIN_EXAMPLE
2010-02-05 Corolla
        Assets:Tilit:OP                 -956 €
        Assets:Auto
; ...
2012-01-05 Corolla myyty
        Assets:Tilit:OP                 700 €
        Assets:Auto
#+END_EXAMPLE

Onko meillä nyt olevinaan vielä 250 euron edestä autoa jossain
tallessa? Ei, jotenkin =Auto=-tili pitää nollata. Tämä on about paras
ratkaisu, jonka olen itse löytänyt:

#+BEGIN_EXAMPLE
2012-01-05 Corolla myyty oikein
        Assets:Tilit:OP                 700 €
        Assets:Auto                     -956 €
        Expenses:Auto
#+END_EXAMPLE

Tässä on se ongelma, että myydessä jotain pitäisi olla tiedossa se
vanha ostohinta, mahdollisesti postikulut vähennettynä. Eikä ole
todellakaan aina mahdollista, kuten kirjanpidon alussa tehtävästä
pääomajutusta tiedämme.

Joten jos joku tietää paremmin oikean tavan tai keksii muuten vain
jotain, niin please, ehdotelkaa. Muuten joudun jonain vuonna vielä
käymään kirjastossa tutustumassa aiheeseen ja sitten muokkailla
vanhoja tapahtumia päivätolkulla.

Ehkä se oikea tapa on vain merkitä kaikki ostettu irtain menoiksi ja
olla sitten autuaan tietämätön hifisettinsä "arvosta".
