#+TITLE: Luksuksista
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Luksuksista                 :sandels:kalorit:talous:elintasoinflaatio:
CLOSED: [2021-11-05 Fri 18:28]
:LOGBOOK:
- State "DONE"       from              [2021-11-05 Fri 18:28]
:END:

Ostin hiljan 5 suklaalevyä tarjouksista ja nyt tuntuu että taidan
antaa ne pois.

Pimeä ja sateinen loppusyksy laittaa Woltin tapaiset palvelut
kiinnostamaan. Voin nyt uuden crosstrainerini kanssa hikoilla kalorit
pois ja syödä isompaa illallista näin halutessani. Maukas burgeri tai
Fafa's-wrappi on ylellisyyttä ja tasapainoista ruokavaliota, joka
mahalaukussa antaisi hohtoa ja dopamiinia iltaansa.

Wolttailu on kivaa ja ravintolassa on ylipäänsä mukava syödä
laadukasta ja vaihtelevaa sapuskaa. Mietin että ottaisinko hyvinkin
tavakseni syödä jossain ravintolassa kerran viikossa.

Taloudellisesti se olisi jotain 60-80 euron välimaastoa
kuukausitasolla, eli hyvin helposti tehtävissä.

Raha-asiat sikseen, enemmän minua harmittaa ajatus tähän luksukseen
tottumisesta. Että ottaisin ravintolaillat itsestäänselvyytenä
ennenpitkää. Että tämä 60-80 euroa olisi välttämättä budjetoitava
kuukausimenoihini, koska ilman ravintolaa en osaisi olla.

Mainitut suklaalevyt ovat hyviä ja sain ne halpana diilinä: 20 senttiä
per levy.

Muutaman palan voin aina syödä päivässä ilman että alkaa kalorihommat
kuumotella liiaksi. Mutta liian pitkäksi jos venyttää tuotakin
makunautintoa, kuten yhtä 85 gramman levyä useaksi päiväksi, alkaa
suklaa olla liian arkipäiväinen nautinto pian.

Nyt kun Sätös on poiskirjoitettu kysymys ja muut erakkotalot voivat
odottaa rauhassa vuoroaan, jää kysymykseksi että mitä ja mihin
mahtaisin säästää rahaa. Sekin kun on kasvavissa määrin potentiaalinen
juttu, että Hyvinkäällä tottuu asumaan ja Helsinkiin ei kaipaakaan
(pitkälti koska asuntolotossa on joskus vaikea voittaa).

Säästö tietysti kannattaa, koska asumis- tai elämäntilanne voi muuttua
mikä tahansa päivä.

Minun on sinänsä helppoa laitella rahaa syrjään ja "kasvatella"
numeroita, mutta joskus se nakertaa kun ei osaa nauttia päivästään
tässä ja nyt.

Onko osa luksuksista perusteltuja, vai enkö ehkä ole löytänyt
"omanlaista" luksusta johon olisi nyt varaa siinä missä aiemmin ei
kenties ollut.

Tämä teksti sai aika kovan nälän aikaan. Woltin sivut ovat tuossa
auki. Miten tässä nyt kävi näin?
