#+TITLE: Käyttämäni MPD-asiakkaat
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Käyttämäni MPD-asiakkaat                                         :mpd:
CLOSED: [2013-05-17 Fri 14:29]
:LOGBOOK:
- State "DONE"       from "TODO"       [2013-05-17 Fri 14:29]
:END:

Kerron, mitä MPD-asiakasohjelmia käytän. Tässä ne tulevat
käyttöjärjestyksessä, ja sitten elaboroin, jos näen tarvetta.

1. [[http://pms.sourceforge.net/][PMS]], eli Practical Music Search
2. [[https://github.com/progo/jazz_up][jazz\_up]] on omakirjoittamani bash-kikkare
3. [[http://www.musicpd.org/clients/mpc/][MPC]] loppuihin kikkailuihin
4. (mpp: C-kikkare, joka tulostaa soittolistan terminaaliin)
5. (mpp\_length.sh: awk-kikkare, jolla katson soittolistan
  kokonaispituuden)

Kunniamaininta annetaan [[http://mpd.wikia.com/wiki/Client:Mpdscribble][MPDScribblelle]], joka on myös klientti ja
teknisesti ottaen täten eniten käyttämäni klientti. MPDScribble
siirtää kuunteluni last.fm -palveluun.

** PMS on simppeli ja tehokas

PMS on ncurses-pohjainen MPD-klientti, jonka filosofiana on puskea
kaikki tietokannan musiikki yhteen ja samaan listaan, jossa
tehdään pinnallisia ja joustavia hakuja. Näppäimet ja toiminta on
hyvin vi-henkistä: =/= aloittaa haun ja =b=-näppäimellä siirretään
kursorin alla olevan kappaleen koko albumi soittolistalle. Iso =B=
vastaavasti lisää albumin ja aloittaa soittamisen siitä
välittömästi. En ole osannut kaivata ylimääräistä joustavuutta,
joten PMS:stä tuli vähitellen pääasiallinen klienttini.

** Jazz\_up nopeita arvontoja varten

Jazz\_up ottaa argumenttinaan minuuttilukeman ja mpd-soittolistan
nimen. Sieltä se sitten alkeellisesti arpoo listalta sellaisia
kappaleita listalle, että minuuttilukema tulee suurinpiirtein
täyteen. Toimii, kun haluaa nopeasti syödä nuudelinsa jonkun
päivällisjazzin kanssa, tai odottelee hiusten kuivamista.

** MPC

MPC on niin yleinen, ettei siitä kamalasti mitään keksi. Käytän
sitä joskus skripteissäni, mutta en kamalasti. Eniten käytetty
kutsu lienee =mpc toggle=, jota ei sitäkään kamalan usein tapahdu.

** Tulevaisuus?

Ehkä MPyD kypsyy ja otan sen käyttöön. Ehkä se toimii hyvin, mutta
en sitten innostukaan omasta keksinnöstäni. Se on varma, että en
aio toteuttaa kaikkea "tarpeellista" MPyD:iin ihan sillä
periaatteella, että PMS, MPC ja muut ovat olemassa ja voivat elää
samanaikaisesti käytössä.
