#+TITLE: Pythonin käsittämätön tehokkuus komentorivisovelluksissa
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Pythonin käsittämätön tehokkuus komentorivisovelluksissa :python:clojure:koodi:cli:
CLOSED: [2015-09-26 Sat 19:20]
:LOGBOOK:
- State "DONE"       from ""           [2015-09-26 Sat 19:20]
:END:

[[python-vs-clojure.org][Clojuren olen tuominnut Pythonia paremmaksi kieleksi]], ja siitä
ylöskirjoittamani mietteet näyttävät edelleen pitävän paikkansa. Miksi
kuitenkin noita Python-ohjelmia tulee kirjoiteltua siitä huolimatta?!

Ohjelmat, joita kirjoitan omaksi ilokseni, ovat yleensä
komentorivipohjaisia. Komentorivillä sovelluksen nopea käynnistyminen
kuuluu käyttömukavuuteen, erityisesti silloin kun operaatio on
muutenkin lyhytkestoinen. Clojure-sovelluksen käynnistyminen vie
edelleen yli sekunnin, vaikka luvut taitaakin saada kymmenesosaan
siitä huolellisella valmistelulla. Python-skripti käynnistyy riittävän
nopeasti kaikkeen mielekkääseen operointiin. Ja tietojenkäsittely,
mitä komentorivilläni tapahtuu, on yleensä luonteeltaan sellaista,
että Pythonin hitaus ei näy missään: joko kovaa laskentaa ei ole, tai
kutsun muita ohjelmia aliprosesseina.

Python on muutenkin selkeä tapa kirjoittaa eräajosovellusta, ja
pienten skriptien tapauksessa kielen ja ympäristön puutteetkin jäävät
varjoon. Ehkä kuitenkin Pythonin ongelmat alitajuntaisesti estävät
minua laajentamasta sovellusta alkuperäisen ominaisuusskoopin
ulkopuolelle, koska se alkaisi herkästi tarkoittaa sitä, että nopeat
hakkaukset pitäisi kirjoittaa paremmin. Clojuressa onkin pikemmin se
ongelma, että kieli vääntää kirjoittajansa kättä aina valitsemaan
Oikeaoppisen Tavan tehdä jokainen pienikin asia, joka 50-rivisessä
pikavirityksessä voi vähän lannistaa. Tämä kuitenkin olisi eduksi, kun
softaan tulee uusia ideoita toteutettavaksi.

Pitäisikö siis hyväksyä tilanne niin päin, että pikaiset skriptit
tulee jatkossakin kirjoitettua Pythonilla ja sitten harkita
uudelleenkirjoitusta Clojurelle "kakkosversion" häämötellessä. Tämä ei
kuulosta realistiselta idealta omaan korvaani. Voiko päätöksenteossa
olla mukana sitäkin tekijää, että Clojurella kirjoittamani
komentorivisoftat ovat vähälukuisia ja siten sellainen alkukankeus
vaivaisi.

Minun pitäisi pikemminkin aloittaa porttamaan pienimpiä
python-skriptejäni Clojurelle ja samalla katsoa, mitä sieltä oppisi
sitä kautta. Ja jos minulla olisi joitain "päivittäiskäytössä"
pyöriviä Clojure-ohjelmia työkalulaukussani, käynnistymisnopeudellekin
tulisi tehtyä ajan saatossa jotain. Näin tulisi myös hiottua
peruskirjastoja, joilla argumentteja parsitaan, kuinka tiedostoja
käsitellään, ja sitä rataa.

ClojureScript (joka kääntyy myös NodeJS-yhteensopivaksi
JavaScriptiksi) olisi yksi vaihtoehto. En kyllä edelleenkään nauti
näistä liittyvistä työkaluista, vaikka tätä nykyä onkin jo helppoa
saada projekti tulille ja suoritettavaksi. Ihmeellisiä eroavaisuuksia
löytyy valitettavan paljon.
