#+TITLE: Raivostuttavat fraasit
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Raivostuttavat fraasit
CLOSED: [2016-08-11 Thu 18:52]
:LOGBOOK:
- State "DONE"       from ""           [2016-08-11 Thu 18:52]
:END:

Esitän rantin kansan käyttämistä termeistä, jotka saavat
irrationaaliset vihat pintaan. Painotus irrationaalisuudelle, koska
näitä tehdään tahtomatta ja usein hyvissä aikeissa. Ja tiedostan, että
ei huonon kielenkäytön takia kannattaisi nostaa paineita. Ne kuitenkin
nostattavat minulle eriasteisia raivon tunteita pintaan. Nyrkkisääntö
on: jos käytät tämmöisiä minun läheisyydessäni, voit odottaa
epäoptimaalista kohtelua, tyypillisesti jätän keskustelun sikseen.

Tähän listaan on lupa odottaa täydennystä.

** "Nykyinen vuosi"

Tämä on typerä argumentti, jota kuulee kaikenlaisissa piireissä
nykyään. Esimerkkinä tämmöiseen olen törmännyt: "nyt on vuosi 2012.
Komentoriville ei ole käyttöä."

Ihan kiva, mutta vuosinumeroiden tapaaminen ääneen ei ole tasan mikään
argumentti. Jos vuosi onkin 2017, onko aiemmin tehty perustelu nyt
vanhentunut vai miten? Osaavimmat kykenevät kertomaan tarkalleen, mikä
epäkohta mättää. Parempi kun tätä ei käytä minun kuullen lainkaan.

** "Teennäinen"

Terminä teennäinen/pretentious on aikalailla typerimmästä päästä. Ai
osaat lukea taiteilijan ajatukset ja täten tiedät varmaksi, milloin
hän teeskentelee? Hyvä homma. Muut käyttävät tätä termiä silloin kun
he haluavat sanoa: "tekisin asian itse toisin".

** Taivutuksen osaamattomuus tai jaksamattomuus

Taistelen tuulimyllyjä vastaan, mutta cs-taivutus etenkin ilmiselvästi
laiskuutta implikoivissa merkeissä ei saa minua myydyksi. Tämä on
pitkälti irrationaalinen viha, kuten tietysti moni muukin näistä:
saanhan minä selvää sanomasta vaikka pääte nyt ei olisikaan mukana
tekstissä. Ja syyllistyn itsekin tähän nykypäivänä kanssa jonkin
verran, mutta en ikinä laiskuuttani! Se ei rasita, jos joudun
keskustelemaan jonkun kanssa, joka jättää koulut kesken yläasteella,
mutta jos joku laiskuuttaan ei jaksa tavata sanoja loppuun asti, saa
minut helposti jättämään koko keskustelun.

** Kovo

Vanha klassikko. Kovo tarkoittaa minulle kaikkea rautaa, ei vain
kovalevyä tai muuta koneensisäistä massamuistia. Pystyn toimimaan, jos
joku käyttää sanaa nykyaikaisella merkityksellä, mutta se joku saa
tehdä kyllä enemmän työtä päästäkseen samalle aallonpituudelle
kanssani.

** Hakemisto/kansio

Tämä on pieni ongelma, mutta huonona päivänä tympii pienikin ongelma.
Unixeissa, linuxissa ja DOS:ssa ei ole kansioita, vaan siellä on
hakemistoja! Windowsissa olevia asioita voi kutsua kummalla tahansa
nimellä. IMAP:ssa on kansioita. Tympii, että graafisissa
työpöytäympäristöissä (ainakin Gnome) suositaan tuota väärää
kansiotermiä.

** Komento/ohjelma

Komentorivillä kirjoitetaan komentoja, jotka vuorostaan käynnistävät
mahdollisesti ohjelmia. Mutta se binääri, joka majailee jossain
tiedostojärjestelmässä, on kuitenkin *ohjelma*, ei komento! Näin yhden
kysymyksen netissä ja siellä kysyjä sanoi, että "tämä hakemisto on
täynnä komentoja". Ei näin.

Tulee myös muistaa, että jokaista komentoa ei välttämättä vastaa
ohjelma: komento voi olla shellin oma sisäänrakennettu toiminto,
tai käyttäjän kirjoittama alias tai funktio.

** Linkki/URL

Kun web-sivulla lukee =google.fi=, mutta ei-klikattavassa muodossa,
niin silloin kyseessä ei ole linkki. Se on puhdasta tekstiä, joka
sattuu olemaan samalla URL. Linkki on hypertekstissä sellainen
elementti, josta voi edetä eteenpäin klikkaamalla tai muiden
tavanomaisin keinoin.

Ainakin Firefoxissa voi maalata paljaan urlin, ja se antaa
kontekstivalikossa valinnan "avata linkin", joten raja on häilyvä.
Menisin mieluummin hypertekstistandardin mukaisin määritelmin, eli jos
HTML-elementti ei ole ankkuri, niin kyseessä ei ole linkki.
JS-webappsit sitten erikseen.

** Komentorivin ja TUI:n ero

Komentorivisovellus on eräajotyyppinen sovellus, eli sellainen, joka
porskuttaa läpi ilman käyttäjän vuorovaikutusta. Kaikki syöte pitäisi
ohjelmalle antaa ennen suorittamisen aloittamista. Ehkä sallin
määritelmään mukaan myös sovellukset, jotka kysyvät yksinkertaisia
vahvistuksia ajon aikana. Nyrkkisääntö on, että komentorivisovellus
toimii yhtä vuorovaikutteisesti niin tietokoneen näytöllä kuin
tulostinpäätteellä.

Monesti kuulee puhuttavan, että =vim=, =irssi= tai =WeeChat= tai
=bash= sen puoleen olisivat komentorivisovelluksia. Nämä ovat kovasti
vuorovaikutteisia ohjelmia. Oikea termi on merkkipohjainen sovellus,
tai TUI (textual user interface).

** ping

Kun mittaan latenssia palvelimeen, käytän ping-nimistä ohjelmaa tähän.
Saatu tulos ei ole kuitenkaan "ping", vaan latenssi. En sano myöskään,
että huoneen lämpömittari on +22 astetta celsiusta.

** Reboot

Tv-sarjojen ja elokuvien yhteydessä puhutaan ns. fransiisin
reboottauksesta eli saman juonen lämmittelystä uusilla ihmisillä,
jotta uudelta sukupolvelta voidaan lypsää samat rahat uudelleen.

Esimerkiksi Batman on rebootattu muutamaan otteeseen, kunkin version
parissa on tehty useita elokuvia ja jokaisella on oma näkemys
asioista. Yksittäisiäkin elokuvia aina reboottaillaan silloin tällöin,
esimerkkinä King Kong ja The Great Gatsby. 

Reboottaus tarkoittaa kuitenkin aina puhtaalta pöydältä lähtemistä.
Siksi on väärin sanoa, että tammikuussa 2016 tapahtunut X-Files oli
reboottaus: se on suoraan jatkoa alkuperäiselle tv-sarjalle,
näyttelijöitä ja juonta myöten. Samoiten vuoden 2017 Twin Peaks ei ole
näillä näkymin rebootti, koska juonta ilmeisesti jatketaan siitä,
mihin jäätiin.

** Meemi vs kuvamakro

Meemit ovat olleet olemassa vuosisatoja, ehkä vuosituhansia. Sekä
kirjallisuudessa ja ehkä enemmän kasuaaleissa keskusteluissa meemejä
viljellään kevennysten ja huumorin nimissä. 

Nyt sitten yhtäkkiä 2000-luvulla termi omittiin tarkoittamaan vain
kuvia, joissa on sovellettu meemiä kuvaan upotettuina otsikkoina.
Erityisen raivostuttavaa on sitten nähdä ihmisiä, jotka näkevät kuvan,
jossa on tekstiä upotettu muista syistä mukaan, ja valittavat kun tämä
ei ole meemi, tai että meemiä olisi käytetty väärin.

Kuvamakrot taitavat olla meemejä kyllä pääosin, mutta kaikki meemit
eivät ole kuvamakroja!

** /thread

Joissain ajanvietekeskusteluissa saattaa joku heittää niin hyvän jutun
ketjun teemaan liittyen, että ihmiset alkavat julistaa ketjua
päättyneeksi. Miksi vitun ihmeessä pitäisi lopettaa hyvä huulenheitto
siihen kun joku keksii heittää ilmoille yhden keskimääräistä paremman
jutun?

** Trollaus

Sarkasmin ja parodian ja /installaatioiden/ käsite on nykyihmisille
kokonaan vieras, ja nyt kaikki on aina ja vain trollaamista. On huono
homma sekoittaa bannattava rike ja kirjallisuuden keinot keskenään
yhden termin alle.

** "It Just Works"

Jobsin uittama myyntifraasi on valitettavan yleinen jopa fiksujen,
teknisiin keskusteluihin kykenevien ihmisten keskuudessa. Fraasin
ongelma on se, että se sanoo liittyvän sovelluksen tai palvelun
/toimivan jotenkin/, mutta ei sano, että miten tarkalleen se toimii
(ja miten se ei ehkä toimi). Se on kaikkein kapeakatseisimpien
käyttötapausten ihannointia. Jos sovellus tarjoaa vähänkin enemmän
vaihtoehtoja ja toimintoja, tätä "arvonimeä" on hankala saavuttaa.

** Tekstiseinä

Vanhaan hyvään aikaan tekstiseinä (Wall of text) oli selkeästi
huonosti ladottu sanapuuro, jota oli vaikea lukea huonon ulkoasun
takia. Esimerkkinä lukiossa eräs lehtori tapasi tehdä A4-luentokalvot
ilman yhtäkään kappalejakoa ja kaikki vielä isoilla kirjaimilla. Siinä
on oikea tekstiseinä! Se oli sitä samaa aikaa kun kouluun piti hiihtää
kesät talvet, molemmat suunnat ylämäkeä.

Nykyjonnet kutsuvat nykyään kaikkea tekstiä tekstiseinäksi, jos seassa
ei ole animoituja giffejä tai youtube-upotuksia. Jopa Hacker Newsissä,
jota ainakin yritän pitää sellaisena aikuisten paikkana, valiteltiin
kerran kun lyhyistä kappaleista (parin virkkeen kappaleita!) koostuva
mustaa-valkoisella ollut sivu oli jonkun kommentoijan mielestä
tekstiseinä. Ei saatana.

** Asiat, jotka eivät häiritse

Löytyy listata myös muutama asia, jotka eivät nypi minua näin pahasti.

- /skripti vs ohjelma/: vaikka näille termeille voisi löytyäkin
  selkeät eroavaisuudet, minua ei haittaa vaikka näitä käytettäisiin
  sekaisin samoissa asiayhteyksissä.
- Emacsin /plugini vs paketti/: Emacsille kirjoitettuja
  elisp-paketteja ei saisi sanoa plugineiksi, koska Emacsissa ei ole
  oikeata plugin-arkkitehtuuria. Termin käyttö implikoisi, että
  Emacsin laajennettavuus olisi rajallisempaa kuin todellisuudessa
  onkaan.
- Hymiöt ennen virkkeiden päätöksiä. Jotkut eivät osaa laittaa
  hymiöitä virkkeen ulkopuolelle, missä ne eivät menisi sekaisin
  pisteiden, huutomerkkien tai muiden virkkeenpäätteiden kanssa. Ei
  haittaa kamalasti, vaikka kiinnitänkin huomiota.
- TL;DR on hyvin typerä ilmiö (miksi koko internetin pitäisi palvella
  laiskoja ihmisiä?), mutta en menetä malttiani kokonaan. Tämä olisi
  paljon kivempi jos puhuttaisiin vaikka tiivistelmästä tämän
  onnettoman lyhenteen sijaan.
- Sarkasmivaroitusten käyttäminen tekstissä. Normiälyisen ihmisen
  tulisi osata erottaa sarkasmi muista mielipiteistä. Ja vaikka tässä
  ei ensimmäisellä kerralla onnistuisikaan, ei kenenkään elämän
  pitäisi siihen kaatua.


