#+TITLE: Vuokra-autoilua
#+SETUPFILE: ~/dokumentit/blog/post-setup.org
* DONE Vuokra-autoilua                                        :sandels:autot:
CLOSED: [2022-03-27 Sun 11:24]
:LOGBOOK:
- State "DONE"       from              [2022-03-27 Sun 11:24]
:END:

Vaikka bensa on kallista näinä päivinä, eikä koronasesongin alhaisia
vuokratarjouksia saa myöskään enää autoista, otin pariksi viikoksi
taas vuokra-autoa alle pääsiäisen ympäriltä. Autoilun joustavuus
tarjoaa suunnattomasti helppoa, matalakynnyksisistä tekemistä
lomaviikon päiville.

** Vuokra-autoilusta uusi tapa

Viime vuonna vuokrasin kahteen otteeseen autoa alle, keväällä ja
syksyllä pariviikkoiset rupeamat. Ekan auton sain vuokrattua tosi
edullisesti, ja sen jälkeen vuokraustarjonta on ollut kalliimpaa.
Tosin Suomen mittakaavassa on edelleen edullista vuokrailla autoa
täällä PK-seudulla.

Keväällä '21 oli eka kerta autoilua Sätöksen jälkeen ja silloin ei
ollut isompaa agendaa -- sen kuin ajelisin ympäriinsä uutta
lähiseutuani. Löysin kivaa ajeltavaa riittävästi.

Toinen kaksiviikkoinen oli syksyllä kesäloman yhteydessä ja silloin
minulla oli selkeä projekti Varsinais-Suomessa, missä minulla oli
vuokrattu kiva rantamökki Paraisissa ja ajelin sitten Turkua ja sitä
seutua isosti. Mikäs siinä kun auto jaksaa kuljettaa.

Nyt on talviloman aika ja piti miettiä että maksanko auton
vuokrauksesta ja kalliista bensasta, vai kyhjötänkö kotona murjottaen.
Auton ratista pääsee nätisti paikkoihin ja ajan saa kulumaan. Vaikka
tämä ei ole halvinta huvittelua maailmassa niin kyllä tämä pienissä
erissä menettelee.

** Paluu auton rattiin

Kirjailin mietteitä auton rattiin hyppäämisestä jo vuosi sitten
huhtikuussa, mutta en julkaissut sitä tekstiä. Pääpointti oli, että
olin Töölössä ehtinyt asettua autottomaan elämäntapaan, ja nautin
siitä että Hyvinkäällä voin jatkaa samaa menoa. Oli siksi vuokrauksen
alussa osittain kurjaa, että kaunista kevätsäätä piti mennä piiloon
peltilehmän suojiin. Siihen ehti onneksi tottua nopeasti ja uusia
paradigmoja aloin hahmotella ja löytää.

Ajelin silloin Hyvinkäätä, ajelin 130-tietä, kävin Valkeakosken
suunnalla, Forssassa ja Hangossa. Auto oli näppärä
automaattihybridi-Yaris, joka toimi minulle hyvin. Notkea kiihtyjä ja
oli joustavaa mennä. Pystyin pakkaamaan paljon kamerakamaa auton
takapenkille ja se oli hieno tapa käytellä kamerakamaa, jota ei ehkä
tavallisesti olisi tullut käyttäneeksi.

Autoilussa on se erinomaisuus, että auto vie pidemmälle kuin mitä omat
lihakset jaksavat. Ja nopeammin kanssa. Tavaraa kulkee mukana, eväitä
ja juomisia myöten. Kun muistaa pysähdellä usein valokuvaamaan, on se
joustavuutta myös valokuvaajalle. Määränpäät voivat olla kauempana
kotiovesta, ja saavut niihin virkeänä.

Koska auto kantaa tarvittaessa kauas, yhtäkkiä huono sääennuste
Hyvinkäällä ei vielä tarkoita koko viikonlopun menetystä. Katsoin
viime huhtikuusssa että Hyvinkäällä olisi tylsä perjantai tulossa
mutta Hangossa näyttäisi olevan auringonlaskun ainekset. Ajelin
Hankoon sitten! Koitapa kävellen tai pyöräillen vaihtaa ilmastoa
tuosta noin vain.

** Oma auto?

Aiemmat kaksi vuokrausta ovat olleet pääsääntöisesti positiivisia ja
odotan innolla tätä kolmatta kanssa. Mutta olisiko edullisempaa
hommata oma auto kuin vuokrailla "jatkuvasti" toista?

Ajatus kiehtoo osittain, mutta ilman omaa lämmityspaikkaa en näe
ajatusta ihan superina. Talvella nousi puheenaiheeksi yksi ehkä
ylimääräiseksi muuttuva Kia, joka saattaisi joutaa ennenpitkää
minulle. Mutta voinko minä pitää edes lahjaksi saatua autoa järkevästi
täällä? Isoja kysymyksiä.

Uskoisin että halunnen olla autotta jatkossakin. Tekisihän se joistain
Hyvinkään ongelmista historiaa, mutta tulisi muita ongelmia tilalle.
Rahaa menee nyt ainakin.

Toisaalta kuten olen tavannut sanoa jo pitkän aikaa: jos ongelmasta
selviää rahalla niin se on hyvälaatuinen ongelma.

Oma auto tuntuisi enemmän omalta idealta, jos pääsisi jonnekin "uuteen
Sätökseen" jollain aikavälillä. Tai, idean ohellahan se on suorastaan
pakollisuus senlaisilla haja-asutusalueilla, joihin haluaisin asettua.

